import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  BonusEntryType,
  DeferredBonusLotStatus,
  LedgerAccountType,
  PostingDirection,
  Prisma,
} from '@prisma/client';
import { Decimal } from '@prisma/client/runtime/library';
import { AppConfig } from '../../config/configuration';
import { PrismaService } from '../../infrastructure/prisma/prisma.service';
import { LedgerService } from '../ledger/ledger.service';
import { BonusEngineService } from './bonus-engine.service';

type Tx = Prisma.TransactionClient;

/**
 * The 30% deferred/"black" pool share — spec §13-16. Deliberately not built
 * on `BonusLot`'s own PENDING→AVAILABLE machinery: that sweep promotes on
 * elapsed *time*, unconditionally, and a deferred lot's unlock condition is
 * cumulative *turnover*, not time. See
 * docs/CORE_ARCHITECTURE_MIGRATION_2026-08.md §3 for the full reasoning.
 *
 * A `DeferredBonusLot` therefore never touches `Wallet`/`BonusLot` until the
 * moment it actually unlocks — the value is not spendable, and does not even
 * exist as a wallet balance, before that.
 */
@Injectable()
export class DeferredBonusLotService {
  private readonly logger = new Logger(DeferredBonusLotService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly bonusEngine: BonusEngineService,
    private readonly config: ConfigService<AppConfig, true>,
    private readonly ledger: LedgerService,
  ) {}

  /**
   * Spec §15: applies one confirmed purchase's full gross amount to every
   * *existing* active deferred lot for this user whose window contains it,
   * unlocking any that cross their threshold — before the caller creates a
   * new lot from this same purchase's own deferred share. Called from
   * `PurchaseIntentService` inside its own transaction, in that order; this
   * method does not create the new lot itself, by design, so a purchase can
   * never progress its own newly-created lot.
   */
  async advanceExistingLots(userId: string, grossAmount: Decimal, tx: Tx): Promise<void> {
    const now = new Date();
    const lots = await tx.deferredBonusLot.findMany({
      where: { userId, status: DeferredBonusLotStatus.DEFERRED, deadline: { gte: now } },
    });

    for (const lot of lots) {
      // Atomic DB-side increment, not a read-modify-write of a JS-computed
      // absolute value: the enclosing transaction (PurchaseIntentsService
      // .settlePurchase) runs at Postgres's default READ COMMITTED, not
      // Serializable, so two purchases confirmed concurrently for the same
      // customer — each progressing this same lot — would otherwise both
      // read the same starting `progressTurnover`, both compute their own
      // "old + this purchase's amount", and the second UPDATE to commit
      // would silently overwrite the first's contribution rather than
      // stacking on top of it, permanently losing turnover the customer
      // genuinely earned. `{ increment: grossAmount }` is evaluated by
      // Postgres against the row's current value at write time, so this is
      // correct regardless of isolation level or how many purchases land at
      // once.
      const updated = await tx.deferredBonusLot.update({
        where: { id: lot.id },
        data: { progressTurnover: { increment: grossAmount } },
      });
      if (updated.progressTurnover.lessThan(updated.requiredTurnover)) {
        continue;
      }

      // Threshold crossed: unlock. Conditional on still being DEFERRED so a
      // concurrent second purchase applying to the same lot cannot unlock it
      // twice — mirrors the claim-then-act pattern the rest of this
      // codebase uses for exactly this reason. `progressTurnover` was
      // already committed atomically above; nothing left to set here but
      // the status transition.
      const claimed = await tx.deferredBonusLot.updateMany({
        where: { id: lot.id, status: DeferredBonusLotStatus.DEFERRED },
        data: {
          status: DeferredBonusLotStatus.AVAILABLE,
          unlockedAt: now,
        },
      });
      if (claimed.count === 0) continue;

      const wallet = await tx.wallet.findUniqueOrThrow({ where: { userId } });
      const granted = await this.bonusEngine.accrue(
        {
          walletId: wallet.id,
          type: BonusEntryType.ACCRUAL_DEFERRED,
          amount: lot.amount,
          sourceTransactionId: lot.sourceTransactionId,
          pendingHours: 0,
          metadata: { deferredBonusLotId: lot.id },
        },
        tx,
      );
      await tx.deferredBonusLot.update({
        where: { id: lot.id },
        data: { grantedBonusLotId: granted.id },
      });
      this.logger.log(`Deferred bonus lot ${lot.id} unlocked for user ${userId}: ${lot.amount} AMD`);
    }
  }

  /**
   * Creates the new deferred lot generated by *this* purchase — spec §13.
   * Its `progressTurnover` starts at zero and this purchase's own gross
   * amount is not applied to it; only *later* purchases can (spec §15).
   */
  async createLot(
    userId: string,
    amount: Decimal,
    sourceTransactionId: string,
    tx: Tx,
  ): Promise<void> {
    if (amount.lessThanOrEqualTo(0)) return;
    const policy = this.config.get('purchasePolicy', { infer: true });
    const deadline = new Date();
    deadline.setMonth(deadline.getMonth() + policy.deferredWindowMonths);

    await tx.deferredBonusLot.create({
      data: {
        userId,
        sourceTransactionId,
        amount,
        requiredTurnover: policy.deferredRequiredTurnover,
        deadline,
      },
    });
  }

  /**
   * Spec §16: a lot whose deadline passes before it qualifies is released —
   * the customer's entitlement to it lapses. CONFIRMED business decision
   * (2026-08-16, hardening-audit §N item 1): the released value is
   * recognized as TuTak revenue at the moment it expires — see `expireOne`
   * for the ledger posting this now makes, atomically with the state
   * transition.
   */
  async expireOverdueLots(): Promise<number> {
    const overdue = await this.prisma.deferredBonusLot.findMany({
      where: { status: DeferredBonusLotStatus.DEFERRED, deadline: { lt: new Date() } },
    });
    let count = 0;
    for (const lot of overdue) {
      if (await this.expireOne(lot)) count += 1;
    }
    if (count > 0) {
      this.logger.log(`Expired ${count} deferred bonus lot(s) past their deadline`);
    }
    return count;
  }

  /**
   * One lot's expiry, claimed and posted atomically: `postContributionLedger`
   * already credited `BONUS_LIABILITY` for this lot's `amount` back when the
   * originating purchase confirmed (spec §14's deferred share is part of
   * that posting's `customerLiability` leg regardless of whether the lot
   * ever unlocks) — the ledger has been carrying this as a liability to the
   * customer since day one, even though the wallet itself never reflected it
   * as spendable (see the class docblock). Expiry without qualifying means
   * that liability will never be paid out, so it is released here — DEBIT
   * `BONUS_LIABILITY` — and the same amount becomes TuTak's own revenue —
   * CREDIT `PLATFORM_REVENUE` — in one transaction with the `EXPIRED`
   * claim, so a lot can never end up expired without the matching revenue
   * recognized, or vice versa.
   */
  private async expireOne(lot: { id: string; amount: Decimal }): Promise<boolean> {
    return this.prisma.$transaction(async (tx) => {
      const claimed = await tx.deferredBonusLot.updateMany({
        where: { id: lot.id, status: DeferredBonusLotStatus.DEFERRED },
        data: { status: DeferredBonusLotStatus.EXPIRED, expiredAt: new Date() },
      });
      if (claimed.count === 0) return false;

      if (lot.amount.greaterThan(0)) {
        const [bonusLiabilityAccount, revenueAccount] = await Promise.all([
          this.ledger.accountFor({ type: LedgerAccountType.BONUS_LIABILITY }, tx),
          this.ledger.accountFor({ type: LedgerAccountType.PLATFORM_REVENUE }, tx),
        ]);
        await this.ledger.post(
          {
            kind: 'deferred_bonus.expired',
            sourceType: 'DeferredBonusLot',
            sourceId: lot.id,
            postings: [
              { accountId: bonusLiabilityAccount.id, direction: PostingDirection.DEBIT, amount: lot.amount },
              { accountId: revenueAccount.id, direction: PostingDirection.CREDIT, amount: lot.amount },
            ],
          },
          tx,
        );
      }
      return true;
    });
  }
}
