import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { BonusEntryType, DeferredBonusLotStatus, Prisma } from '@prisma/client';
import { Decimal } from '@prisma/client/runtime/library';
import { AppConfig } from '../../config/configuration';
import { PrismaService } from '../../infrastructure/prisma/prisma.service';
import { BonusEngineService } from './bonus-engine.service';

type Tx = Prisma.TransactionClient;

/**
 * The 30% deferred/"black" pool share — spec §13-16. Deliberately not built
 * on `BonusLot`'s own PENDING→AVAILABLE machinery: that sweep promotes on
 * elapsed *time*, unconditionally, and a deferred lot's unlock condition is
 * cumulative *turnover*, not time. See
 * docs/CORE_ARCHITECTURE_MIGRATION_2026-08.md §3 for the full reasoning.
 *
 * A `DeferredBonusLot` therefore never touches `Wallet`/`BonusLot` until the
 * moment it actually unlocks — the value is not spendable, and does not even
 * exist as a wallet balance, before that.
 */
@Injectable()
export class DeferredBonusLotService {
  private readonly logger = new Logger(DeferredBonusLotService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly bonusEngine: BonusEngineService,
    private readonly config: ConfigService<AppConfig, true>,
  ) {}

  /**
   * Spec §15: applies one confirmed purchase's full gross amount to every
   * *existing* active deferred lot for this user whose window contains it,
   * unlocking any that cross their threshold — before the caller creates a
   * new lot from this same purchase's own deferred share. Called from
   * `PurchaseIntentService` inside its own transaction, in that order; this
   * method does not create the new lot itself, by design, so a purchase can
   * never progress its own newly-created lot.
   */
  async advanceExistingLots(userId: string, grossAmount: Decimal, tx: Tx): Promise<void> {
    const now = new Date();
    const lots = await tx.deferredBonusLot.findMany({
      where: { userId, status: DeferredBonusLotStatus.DEFERRED, deadline: { gte: now } },
    });

    for (const lot of lots) {
      const progress = lot.progressTurnover.plus(grossAmount);
      if (progress.lessThan(lot.requiredTurnover)) {
        await tx.deferredBonusLot.update({
          where: { id: lot.id },
          data: { progressTurnover: progress },
        });
        continue;
      }

      // Threshold crossed: unlock. Conditional on still being DEFERRED so a
      // concurrent second purchase applying to the same lot cannot unlock it
      // twice — mirrors the claim-then-act pattern the rest of this
      // codebase uses for exactly this reason.
      const claimed = await tx.deferredBonusLot.updateMany({
        where: { id: lot.id, status: DeferredBonusLotStatus.DEFERRED },
        data: {
          progressTurnover: progress,
          status: DeferredBonusLotStatus.AVAILABLE,
          unlockedAt: now,
        },
      });
      if (claimed.count === 0) continue;

      const wallet = await tx.wallet.findUniqueOrThrow({ where: { userId } });
      const granted = await this.bonusEngine.accrue(
        {
          walletId: wallet.id,
          type: BonusEntryType.ACCRUAL_DEFERRED,
          amount: lot.amount,
          sourceTransactionId: lot.sourceTransactionId,
          pendingHours: 0,
          metadata: { deferredBonusLotId: lot.id },
        },
        tx,
      );
      await tx.deferredBonusLot.update({
        where: { id: lot.id },
        data: { grantedBonusLotId: granted.id },
      });
      this.logger.log(`Deferred bonus lot ${lot.id} unlocked for user ${userId}: ${lot.amount} AMD`);
    }
  }

  /**
   * Creates the new deferred lot generated by *this* purchase — spec §13.
   * Its `progressTurnover` starts at zero and this purchase's own gross
   * amount is not applied to it; only *later* purchases can (spec §15).
   */
  async createLot(
    userId: string,
    amount: Decimal,
    sourceTransactionId: string,
    tx: Tx,
  ): Promise<void> {
    if (amount.lessThanOrEqualTo(0)) return;
    const policy = this.config.get('purchasePolicy', { infer: true });
    const deadline = new Date();
    deadline.setMonth(deadline.getMonth() + policy.deferredWindowMonths);

    await tx.deferredBonusLot.create({
      data: {
        userId,
        sourceTransactionId,
        amount,
        requiredTurnover: policy.deferredRequiredTurnover,
        deadline,
      },
    });
  }

  /**
   * Spec §16: a lot whose deadline passes before it qualifies is released —
   * the customer's entitlement to it lapses. This is a product/ledger state
   * transition only; it does not post any revenue recognition for TuTak.
   * TODO: LEGAL / ACCOUNTING REVIEW REQUIRED — see
   * docs/CORE_ARCHITECTURE_MIGRATION_2026-08.md §5.
   */
  async expireOverdueLots(): Promise<number> {
    const result = await this.prisma.deferredBonusLot.updateMany({
      where: { status: DeferredBonusLotStatus.DEFERRED, deadline: { lt: new Date() } },
      data: { status: DeferredBonusLotStatus.EXPIRED, expiredAt: new Date() },
    });
    if (result.count > 0) {
      this.logger.log(`Expired ${result.count} deferred bonus lot(s) past their deadline`);
    }
    return result.count;
  }
}
