import { BadRequestException, Body, Controller, Get, Post, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { PermissionName, SettlementPeriodicity } from '@prisma/client';
import { IsIn, IsInt, IsOptional, Max, Min } from 'class-validator';
import { RequirePermissions } from '../../common/decorators/permissions.decorator';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { UuidParam } from '../../common/decorators/uuid-param.decorator';
import { assertPartnerScope, assertPlatformAdmin } from '../../common/auth/partner-scope';
import { RequestUser } from '../auth/types/request-user.type';
import { PartnerSettlementService } from '../partner-settlements/partner-settlement.service';
import { PartnerSettlementStatementService } from './partner-settlement-statement.service';

export class SetSettlementPeriodicityDto {
  @IsIn(Object.values(SettlementPeriodicity))
  periodicity: SettlementPeriodicity;

  /** 1-7 (Mon-Sun) for WEEKLY/BIWEEKLY, 1-28 for MONTHLY; ignored for DAILY. */
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(28)
  anchorDay?: number;
}

/**
 * Spec §50-52, §77: the partner's settlement view — read-only reporting over
 * the one settlement engine (`PartnerSettlementService`). There is no
 * withdraw endpoint anywhere. The cadence is `Partner.settlementPeriodicity`,
 * a platform admin setting, never the partner's own.
 */
@ApiTags('settlement')
@ApiBearerAuth()
@Controller('settlement')
export class PartnerSettlementController {
  constructor(
    private readonly statements: PartnerSettlementStatementService,
    private readonly engine: PartnerSettlementService,
  ) {}

  @Get('partners/:partnerId/summary')
  @RequirePermissions(PermissionName.PARTNER_TRANSACTIONS_READ)
  summary(@CurrentUser() user: RequestUser, @UuidParam('partnerId') partnerId: string) {
    assertPartnerScope(user, partnerId);
    return this.statements.balanceSummary(partnerId);
  }

  /** The last closed periods of the partner's cadence, as statement summaries. */
  @Get('partners/:partnerId/statements')
  @RequirePermissions(PermissionName.PARTNER_TRANSACTIONS_READ)
  list(@CurrentUser() user: RequestUser, @UuidParam('partnerId') partnerId: string) {
    assertPartnerScope(user, partnerId);
    return this.statements.recentPeriods(partnerId);
  }

  /** One period's statement, line by line: `?at=<ISO instant inside the period>`. */
  @Get('partners/:partnerId/statement')
  @RequirePermissions(PermissionName.PARTNER_TRANSACTIONS_READ)
  period(@CurrentUser() user: RequestUser, @UuidParam('partnerId') partnerId: string, @Query('at') at?: string) {
    assertPartnerScope(user, partnerId);
    if (!at) throw new BadRequestException('at is required');
    return this.statements.periodStatementAt(partnerId, new Date(at));
  }

  /** A statement generated by the retired Partner Commerce generator (history). */
  @Get('statements/:id')
  @RequirePermissions(PermissionName.PARTNER_TRANSACTIONS_READ)
  async get(@CurrentUser() user: RequestUser, @UuidParam('id') id: string) {
    const statement = await this.statements.legacyStatement(id);
    assertPartnerScope(user, statement.partnerId);
    return statement;
  }

  @Post('partners/:partnerId/period')
  @RequirePermissions(PermissionName.PARTNER_MANAGE)
  setPeriod(@CurrentUser() admin: RequestUser, @UuidParam('partnerId') partnerId: string, @Body() dto: SetSettlementPeriodicityDto) {
    assertPlatformAdmin(admin, 'Changing a partner settlement cadence');
    return this.engine.setPeriodicity({ partnerId, periodicity: dto.periodicity, anchorDay: dto.anchorDay, actorId: admin.id });
  }
}
