/**
 * Dynamic config, not app.json, so the API target can vary by build profile.
 * `apiBaseUrl` used to be hardcoded to localhost — a build produced this way
 * could never reach anything but a developer's own machine. eas.json sets
 * API_BASE_URL per profile; this file just forwards whatever is in the
 * environment at build time.
 */
/**
 * `eas init` cannot write into a dynamic config — it can only edit app.json —
 * so it prints the project id and leaves placing it to you. Rather than make
 * that a manual edit of this file, the id is read from either the
 * EAS_PROJECT_ID environment variable or an `eas-project.json` next to this
 * file, whichever is present. `apps/mobile/README.md` has the one command
 * that writes it. A project id is not a secret; it is an account-specific
 * value, which is why the repository does not carry one.
 */
function easProjectId() {
  if (process.env.EAS_PROJECT_ID) return process.env.EAS_PROJECT_ID;
  try {
    return require('./eas-project.json').projectId;
  } catch {
    return undefined;
  }
}

const LOCAL_HOST = /^https?:\/\/(localhost|127\.0\.0\.1|\[::1\])(:|\/|$)/i;

/**
 * Where this build will send its requests — and a refusal to produce a build
 * that cannot send them anywhere.
 *
 * A development build is different from every other kind: it is installed
 * next to a Metro server on the same network, and `localhost` is rewritten at
 * runtime to the address the bundle arrived from (see
 * `src/data/api/apiBaseUrl.ts`). So localhost is correct there and only
 * there.
 *
 * A preview or production build has no Metro server. Nothing rewrites the
 * address, so `localhost` means the phone itself and every request fails
 * against a device with no API on it. The app installs, opens, looks right
 * and does nothing — which costs a cloud build, an install, and the time of
 * whoever was being shown it before anyone works out why.
 *
 * Failing here instead is much cheaper. EAS evaluates this file before it
 * queues the build, so a missing API_BASE_URL is a message in the first
 * seconds rather than a dead APK twenty minutes later.
 */
/**
 * A production build may never call itself the demonstration.
 *
 * `demo/` is a separate, generated Expo app with a static `app.json`; it is
 * the only thing in this repository that sets `appEnv: 'demo'`, and the
 * mobile client requires that value *and* `useMocks` before it will answer
 * itself instead of a server (see `src/data/api/mockGate.ts`). The mock
 * transport accepts any credentials, so the distance between those two
 * states has to be structural rather than a matter of care.
 *
 * This is the second lock. Even if somebody set `APP_ENV=demo` on an EAS
 * profile, no build comes out — the config refuses before the build is
 * queued, which costs seconds instead of shipping an installable app with no
 * authentication in it.
 */
function refuseDemoEnv(appEnv) {
  if (appEnv === 'demo') {
    throw new Error(
      'APP_ENV is "demo", which this config will not build.\n\n' +
        'The demonstration is a separate app: `demo/` in this repository, generated by ' +
        'scripts/build-demo-app.sh and run with `npm install && npx expo start`. It answers ' +
        'every request from memory and accepts any credentials, which is safe there and is an ' +
        'authentication bypass in anything installed as TuTak.\n\n' +
        'If you want a build that talks to a real API, set APP_ENV to development, preview or ' +
        'production and give it API_BASE_URL.',
    );
  }
}

/**
 * Whether this build carries the diagnostic overlay.
 *
 * Refused outright for `production`. The overlay covers the lower part of
 * every screen and prints field labels, and a diagnostic surface in a shipped
 * app is the kind of thing that gets noticed by a store reviewer rather than
 * by us. Same reasoning as `refuseDemoEnv`: make the wrong combination
 * impossible to build rather than unlikely to be built.
 */
function diagnosticsEnabled() {
  const on = process.env.DIAGNOSTICS === '1';
  if (on && (process.env.APP_ENV ?? 'development') === 'production') {
    throw new Error(
      'DIAGNOSTICS=1 with APP_ENV=production. The diagnostic overlay draws over the app and ' +
        'names every field on screen; it belongs in the `diagnostic` build profile and nowhere ' +
        'that anybody installs as TuTak.',
    );
  }
  return on;
}

function apiBaseUrl() {
  const appEnv = process.env.APP_ENV ?? 'development';
  refuseDemoEnv(appEnv);
  const configured = process.env.API_BASE_URL;

  if (appEnv === 'development') {
    return configured ?? 'http://localhost:4000/v1';
  }

  if (!configured) {
    throw new Error(
      `API_BASE_URL is not set and APP_ENV is "${appEnv}". A ${appEnv} build has no Metro ` +
        'server to borrow an address from, so it would ship pointing at the phone itself and ' +
        'every request would fail.\n\n' +
        'Set it for this build profile, e.g.\n' +
        '  eas env:create --name API_BASE_URL --value https://your-api.example.com/v1 ' +
        '--environment preview\n\n' +
        'If you deployed the demonstration described in docs/INVESTOR_DEMO_RU.md, the value is ' +
        'the API service URL Render assigned, with /v1 on the end.',
    );
  }

  if (LOCAL_HOST.test(configured)) {
    throw new Error(
      `API_BASE_URL is "${configured}" and APP_ENV is "${appEnv}". On a phone, localhost is the ` +
        'phone — this build could only ever talk to itself. Point it at a reachable address.',
    );
  }

  return configured;
}

module.exports = ({ config }) => ({
  ...config,
  name: 'TuTak',
  slug: 'tutak',
  version: '0.1.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  // v2 is a light-only release (TUTAK_V2_CLAUDE_READ_FIRST.md: "the v2
  // customer release is light-only... neither a fresh nor an existing
  // customer [may] silently land in the legacy dark shell"). 'automatic'
  // would hand a system-driven scheme to anything the app had not painted
  // itself, which is exactly the partial-dark outcome that document forbids.
  userInterfaceStyle: 'light',
  scheme: 'tutak',
  splash: {
    image: './assets/splash-icon.png',
    resizeMode: 'contain',
    // The v2 app's own ground colour (`canvas` in TUTAK_V2_TOKENS.json /
    // `neutral[50]` in packages/design), so the splash does not flash the
    // legacy dark shell before the first frame renders.
    backgroundColor: '#F8F9FB',
  },
  assetBundlePatterns: ['**/*'],
  ios: {
    supportsTablet: false,
    bundleIdentifier: 'am.tutak.app',
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#0A0A0F',
    },
    package: 'am.tutak.app',
    permissions: ['CAMERA'],
  },
  // The browser target is a convenience for looking at the app on a laptop —
  // it is stated explicitly so a future Expo default cannot silently move the
  // build onto a different bundler than the one the native builds use.
  web: {
    bundler: 'metro',
    output: 'single',
    // Without this every page load logs a 404 for the favicon the browser
    // asks for on its own.
    favicon: './assets/icon.png',
  },
  plugins: [
    [
      'expo-camera',
      {
        cameraPermission: 'TuTak needs camera access to scan QR codes for payments.',
        // `expo-camera` can record video, so its plugin adds RECORD_AUDIO on
        // Android by default. This app points the camera at a QR code and
        // reads it; it has never recorded anything. A loyalty app asking for
        // the microphone is a reason to decline the install, and a question
        // at store review that has no good answer.
        recordAudioAndroid: false,
      },
    ],
    // Wires the native Sentry SDKs into the iOS/Android projects EAS builds
    // and adds the build-phase scripts that upload debug symbols/source
    // maps. `authToken` is deliberately not passed here: those native
    // scripts invoke `sentry-cli`, which reads `SENTRY_AUTH_TOKEN` straight
    // from the build environment on its own. Routing it through this file
    // would mean a secret sitting in `extra` in the app manifest — see
    // docs/SENTRY_SETUP.md. `organization`/`project`/`url` are not secrets;
    // they only say which Sentry project the symbols belong to.
    [
      '@sentry/react-native/expo',
      {
        organization: process.env.SENTRY_ORG,
        project: process.env.SENTRY_PROJECT,
        url: process.env.SENTRY_URL,
      },
    ],
  ],
  extra: {
    apiBaseUrl: apiBaseUrl(),
    appEnv: process.env.APP_ENV ?? 'development',
    /**
     * The on-screen event log. Only the `diagnostic` EAS profile sets this,
     * and it refuses to combine with production below.
     *
     * It exists because four hypotheses about the flickering fields have been
     * wrong, each reasoned from this source and each falsified by the next
     * fact from a handset. The overlay replaces "what does it look like" with
     * a timestamped list of what actually happened.
     */
    diagnostics: diagnosticsEnabled(),
    /**
     * Shown by the overlay, and read by `app/sentry.ts` as the Sentry
     * `release` — the same commit-SHA value `apps/api`, `apps/admin` and
     * `apps/partner` tag their own events with (see `@tutak/observability`'s
     * `resolveReleaseSha`). The single most expensive question in this whole
     * episode has been "which version is on the phone" — a build that states
     * its own commit cannot be mistaken for the one before it. `GIT_COMMIT_SHA`
     * is the canonical override; EAS and GitHub Actions each set one of the
     * other two on their own builders, and a local run has none of them.
     */
    commit:
      process.env.GIT_COMMIT_SHA ??
      process.env.EAS_BUILD_GIT_COMMIT_HASH ??
      process.env.GITHUB_SHA ??
      '',
    // Pinned, not omitted. An absent key and a false one behave identically
    // today; only one of them still says no if a future edit starts merging
    // `extra` from somewhere else.
    useMocks: false,
    // A DSN identifies a Sentry *project*, not a secret — publishing it does
    // not let anyone read events, only send new ones tagged as this app. Off
    // (Sentry never initializes) when unset, same "off unless configured"
    // posture the API's OTel/Sentry setup uses. See docs/SENTRY_SETUP.md.
    sentryDsn: process.env.SENTRY_DSN ?? '',
    eas: {
      projectId: easProjectId(),
    },
  },
});
