export enum PartnerOrderPaymentStatus {
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum PartnerOrderStatus {
  CREATED = 'CREATED',
  PAID = 'PAID',
  PARTNER_SEEN = 'PARTNER_SEEN',
  STOCK_CONFIRMED = 'STOCK_CONFIRMED',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  SOURCING_REQUIRED = 'SOURCING_REQUIRED',
  SOURCING_IN_PROGRESS = 'SOURCING_IN_PROGRESS',
  CUSTOMER_DECISION_REQUIRED = 'CUSTOMER_DECISION_REQUIRED',
  ACCEPTED = 'ACCEPTED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  SHIPPED = 'SHIPPED',
  PICKUP_READY = 'PICKUP_READY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum SourcingTaskStatus {
  OPEN = 'OPEN',
  SEARCHING = 'SEARCHING',
  FOUND_EXACT = 'FOUND_EXACT',
  FOUND_ALTERNATE = 'FOUND_ALTERNATE',
  NOT_FOUND = 'NOT_FOUND',
  RESOLVED = 'RESOLVED',
}

export enum PartnerOrderAdjustmentType {
  PRICE_DECREASE = 'PRICE_DECREASE',
  PRICE_INCREASE = 'PRICE_INCREASE',
  ALTERNATE_PRODUCT = 'ALTERNATE_PRODUCT',
  SOURCING_FAILED_REFUND = 'SOURCING_FAILED_REFUND',
  OUT_OF_STOCK_REFUND = 'OUT_OF_STOCK_REFUND',
}

export enum PartnerOrderAdjustmentStatus {
  PENDING_CUSTOMER = 'PENDING_CUSTOMER',
  CUSTOMER_ACCEPTED = 'CUSTOMER_ACCEPTED',
  CUSTOMER_DECLINED = 'CUSTOMER_DECLINED',
  APPLIED = 'APPLIED',
}

export enum OrderEscalationType {
  NOT_SEEN_5MIN = 'NOT_SEEN_5MIN',
  STOCK_NOT_CONFIRMED_30MIN = 'STOCK_NOT_CONFIRMED_30MIN',
  STOCK_NOT_CONFIRMED_REPEAT = 'STOCK_NOT_CONFIRMED_REPEAT',
}
