/**
 * Emits the token set as CSS custom properties so the web apps consume the
 * exact same values as React Native rather than a hand-copied approximation.
 * Consumed by `packages/design/tutak.css`, which is generated by
 * `pnpm --filter @tutak/design build:css`.
 */
import { palette, semantic } from './tokens/color';
import { fontFamily, fontSize, fontWeight, letterSpacing, lineHeight } from './tokens/typography';
import { elevation, layout, radius, space } from './tokens/layout';
import { duration, easing } from './tokens/motion';

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

export function buildCssVariables(): string {
  const lines: string[] = [];

  for (const [rampName, ramp] of Object.entries(palette)) {
    for (const [step, value] of Object.entries(ramp)) {
      lines.push(`  --tutak-color-${kebab(rampName)}-${step}: ${value};`);
    }
  }

  for (const [name, value] of Object.entries(semantic)) {
    lines.push(`  --tutak-${kebab(name)}: ${value};`);
  }

  lines.push(`  --tutak-font-sans: ${fontFamily.sans};`);
  lines.push(`  --tutak-font-mono: ${fontFamily.mono};`);

  for (const [name, value] of Object.entries(fontSize)) {
    lines.push(`  --tutak-text-${kebab(name)}: ${value}px;`);
  }
  for (const [name, value] of Object.entries(lineHeight)) {
    lines.push(`  --tutak-leading-${kebab(name)}: ${value}px;`);
  }
  for (const [name, value] of Object.entries(fontWeight)) {
    lines.push(`  --tutak-weight-${kebab(name)}: ${value};`);
  }
  for (const [name, value] of Object.entries(letterSpacing)) {
    lines.push(`  --tutak-tracking-${kebab(name)}: ${value / 16}rem;`);
  }

  for (const [name, value] of Object.entries(space)) {
    lines.push(`  --tutak-space-${name}: ${value}px;`);
  }
  for (const [name, value] of Object.entries(radius)) {
    lines.push(`  --tutak-radius-${kebab(name)}: ${value === 9999 ? '9999px' : `${value}px`};`);
  }
  for (const [name, value] of Object.entries(elevation)) {
    lines.push(`  --tutak-shadow-${kebab(name)}: ${value.web};`);
  }
  for (const [name, value] of Object.entries(layout)) {
    lines.push(`  --tutak-layout-${kebab(name)}: ${value}px;`);
  }
  for (const [name, value] of Object.entries(duration)) {
    lines.push(`  --tutak-duration-${kebab(name)}: ${value}ms;`);
  }
  for (const [name, value] of Object.entries(easing)) {
    lines.push(`  --tutak-ease-${kebab(name)}: ${value};`);
  }

  return `:root {\n${lines.join('\n')}\n}\n`;
}
