// Product lines from the manufacturer's "Brand Book & Product Collection
// 2027" (Drive Int. AG, Hergiswil, Switzerland; factory Drive Italy S.R.L.),
// supplied by the store owner on 2026-09-23 as a PDF.
//
// The English tagline/description is the manufacturer's own wording (shortened
// where noted). The hy/ru/it texts are the store's translations of it.
// Prices are NOT in the brand book: `demoPriceAmd` is a placeholder the owner
// must replace (priceIsDemo = true). Accent colours are taken from each line's
// pages in the brand book and are a UI choice, not a manufacturer fact.

import type { Locale } from "../../src/generated/prisma/enums";

type L = Record<Locale, string>;
export type Format = "VENT_CLIP" | "HANGING" | "BOTTLE" | "PAPER" | "OTHER";

export type Line = {
  slug: string;
  sortOrder: number;
  accent: string;
  /** Hero art cropped from the brand book (public/brand/lines/<slug>.webp). */
  hero: boolean;
  format: Format;
  /** "45 days" is printed on this line's packaging (seen on the packshots). */
  days45: boolean;
  demoPriceAmd: number;
  /** Product name prefix, e.g. "Little Joe Thumbs Up". */
  prefix: L;
  name: L;
  tagline: L;
  description: L;
  /** Brand-book page (for the source note). */
  page: number;
};

const same = (s: string): L => ({ hy: s, ru: s, it: s, en: s });

export const LINES: Line[] = [
  {
    slug: "little-joe",
    sortOrder: 1,
    accent: "#1E88E5",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 2900,
    page: 6,
    prefix: same("Little Joe"),
    name: { hy: "Little Joe Standard", ru: "Little Joe Standard", it: "Little Joe Standard", en: "Little Joe Standard" },
    tagline: { hy: "Բնօրինակը։", ru: "Оригинал.", it: "L'originale.", en: "The original." },
    description: {
      en: "Designed in Switzerland and manufactured in Italy, Little Joe® combines playful design with premium fragrance technology. Its dual-clip system fits securely into virtually every vehicle air vent for an even fragrance release.",
      ru: "Разработан в Швейцарии и произведён в Италии. Little Joe® сочетает игривый дизайн с премиальной технологией аромата. Двойной зажим надёжно держится практически в любом дефлекторе и равномерно распределяет аромат.",
      it: "Progettato in Svizzera e prodotto in Italia, Little Joe® unisce un design giocoso a una tecnologia di fragranza premium. Il doppio clip si fissa saldamente a quasi tutte le bocchette d'aria per una diffusione uniforme.",
      hy: "Նախագծված է Շվեյցարիայում և արտադրված Իտալիայում։ Little Joe®-ն համատեղում է խաղային դիզայնն ու պրեմիում բուրավետման տեխնոլոգիան։ Կրկնակի ամրակը հուսալիորեն ամրանում է գրեթե ցանկացած օդափոխիչի վրա և հավասարաչափ տարածում բույրը։",
    },
  },
  {
    slug: "thumbs-up",
    sortOrder: 2,
    accent: "#F28FB0",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 3200,
    page: 11,
    prefix: same("Little Joe Thumbs Up"),
    name: same("Little Joe Thumbs Up"),
    tagline: {
      en: "One gesture with a thousand emotions.",
      ru: "Один жест — тысяча эмоций.",
      it: "Un gesto, mille emozioni.",
      hy: "Մեկ ժեստ՝ հազար հույզ։",
    },
    description: {
      en: "Say thank you, well done or good luck — this cheerful character turns every journey into a positive statement, with premium fragrance performance and a playful design.",
      ru: "Скажите «спасибо», «молодец» или «удачи» — этот весёлый персонаж превращает каждую поездку в позитив. Премиальный аромат и игривый дизайн.",
      it: "Grazie, ben fatto, buona fortuna: questo personaggio allegro trasforma ogni viaggio in un messaggio positivo, con una fragranza premium e un design giocoso.",
      hy: "Ասեք «շնորհակալություն», «ապրես» կամ «հաջողություն». այս ուրախ կերպարը յուրաքանչյուր ճանապարհորդություն դարձնում է դրական։ Պրեմիում բույր և խաղային դիզայն։",
    },
  },
  {
    slug: "winter-edition",
    sortOrder: 3,
    accent: "#C9A227",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 3200,
    page: 14,
    prefix: same("Little Joe"),
    name: { hy: "Ձմեռային հավաքածու", ru: "Зимняя коллекция", it: "Edizione invernale", en: "Christmas & Winter Edition" },
    tagline: {
      en: "Celebrate every journey. Celebrate the season.",
      ru: "Празднуйте каждую поездку и каждый сезон.",
      it: "Celebra ogni viaggio. Celebra la stagione.",
      hy: "Տոնեք յուրաքանչյուր ճանապարհ և յուրաքանչյուր սեզոն։",
    },
    description: {
      en: "The warmth, joy and magic of the festive season for every drive, inspired by winter's most beloved fragrances.",
      ru: "Тепло, радость и волшебство праздников в каждой поездке — по мотивам самых любимых зимних ароматов.",
      it: "Il calore, la gioia e la magia delle feste in ogni viaggio, ispirati alle fragranze invernali più amate.",
      hy: "Տոների ջերմությունը, ուրախությունն ու կախարդանքը յուրաքանչյուր ճանապարհին՝ ոգեշնչված ձմռան ամենասիրված բույրերով։",
    },
  },
  {
    slug: "best-mom-dad",
    sortOrder: 4,
    accent: "#E53945",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 3200,
    page: 16,
    prefix: same("Little Joe"),
    name: { hy: "Լավագույն մայրիկ և հայրիկ", ru: "Лучшая мама и папа", it: "Migliore mamma e papà", en: "Best Mom & Dad" },
    tagline: {
      en: "Because some heroes deserve to be celebrated every day.",
      ru: "Потому что некоторых героев стоит чествовать каждый день.",
      it: "Perché alcuni eroi meritano di essere celebrati ogni giorno.",
      hy: "Որովհետև որոշ հերոսներ արժանի են ամեն օր մեծարվելու։",
    },
    description: {
      en: "A small gift with a heartfelt message — for Mother's Day, Father's Day, birthdays or simply to say thank you.",
      ru: "Маленький подарок с тёплым посланием — ко Дню матери, Дню отца, дню рождения или просто чтобы сказать спасибо.",
      it: "Un piccolo regalo con un messaggio sincero: per la festa della mamma, del papà, un compleanno o semplicemente per dire grazie.",
      hy: "Փոքրիկ նվեր՝ ջերմ ուղերձով․ Մայրերի և Հայրերի օրվա, ծննդյան կամ պարզապես շնորհակալություն ասելու համար։",
    },
  },
  {
    slug: "i-love",
    sortOrder: 5,
    accent: "#D7191F",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 3200,
    page: 18,
    prefix: same("Little Joe"),
    name: same("Little Joe I ♥ You"),
    tagline: {
      en: "Carry your passion wherever you go.",
      ru: "Берите с собой то, что любите.",
      it: "Porta con te ciò che ami.",
      hy: "Ձեր սերը՝ միշտ ձեզ հետ։",
    },
    description: {
      en: "Everyone has something they love. Little Joe® I LOVE… keeps what you love close, wherever you go.",
      ru: "У каждого есть то, что он любит. Little Joe® I LOVE… держит любимое рядом, куда бы вы ни ехали.",
      it: "Ognuno ha qualcosa che ama. Little Joe® I LOVE… tiene vicino ciò che ami, ovunque tu vada.",
      hy: "Յուրաքանչյուրն ունի մի բան, որ սիրում է։ Little Joe® I LOVE…-ն սիրելին պահում է մոտ՝ ուր էլ գնաք։",
    },
  },
  {
    slug: "soccer",
    sortOrder: 6,
    accent: "#2E9E4F",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 3200,
    page: 20,
    prefix: same("Little Joe Soccer"),
    name: { hy: "Little Joe Ֆուտբոլ", ru: "Little Joe Футбол", it: "Little Joe Calcio", en: "Little Joe Soccer" },
    tagline: {
      en: "Support your team. Enjoy every journey.",
      ru: "Болейте за свою команду в каждой поездке.",
      it: "Tifa la tua squadra. Goditi ogni viaggio.",
      hy: "Աջակցեք ձեր թիմին յուրաքանչյուր ճանապարհին։",
    },
    description: {
      en: "Football is a language spoken around the world. The Soccer Collection lets fans show their passion while enjoying long-lasting freshness.",
      ru: "Футбол — язык, понятный всему миру. Коллекция Soccer позволяет болельщикам показать свою страсть и наслаждаться стойким ароматом.",
      it: "Il calcio è una lingua parlata in tutto il mondo. La collezione Soccer permette ai tifosi di mostrare la propria passione con una freschezza duratura.",
      hy: "Ֆուտբոլը ողջ աշխարհին հասկանալի լեզու է։ Soccer հավաքածուն թույլ է տալիս երկրպագուներին ցույց տալ իրենց կիրքը և վայելել երկարատև թարմությունը։",
    },
  },
  {
    slug: "love-edition",
    sortOrder: 7,
    accent: "#B79BD9",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 5500,
    page: 32,
    prefix: same("Little Joe & Little Joya"),
    name: same("Little Joe & Little Joya Love Edition"),
    tagline: {
      en: "Two characters. One perfect match.",
      ru: "Два персонажа — идеальная пара.",
      it: "Due personaggi. Un'intesa perfetta.",
      hy: "Երկու կերպար՝ կատարյալ զույգ։",
    },
    description: {
      en: "Little Joe® meets Little Joya® in a special duo made to share: two characters, two personalities and one irresistible fragrance experience.",
      ru: "Little Joe® встречает Little Joya® в особом дуэте, созданном, чтобы делиться: два персонажа, два характера и один неотразимый аромат.",
      it: "Little Joe® incontra Little Joya® in un duo speciale da condividere: due personaggi, due personalità e un'unica fragranza irresistibile.",
      hy: "Little Joe®-ն հանդիպում է Little Joya®-ին՝ կիսվելու համար ստեղծված զույգում․ երկու կերպար, երկու բնավորություն և մեկ անդիմադրելի բույր։",
    },
  },
  {
    slug: "little-joya",
    sortOrder: 8,
    accent: "#F2B8CC",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 2900,
    page: 54,
    prefix: same("Little Joya"),
    name: same("Little Joya"),
    tagline: {
      en: "A character of her own.",
      ru: "Персонаж с собственным характером.",
      it: "Un personaggio tutto suo.",
      hy: "Իր սեփական բնավորությամբ կերպար։",
    },
    description: {
      en: "Confident, colourful and full of personality, Little Joya® brings a fresh, feminine touch to every journey.",
      ru: "Уверенная, яркая и с характером — Little Joya® добавляет свежую, женственную нотку в каждую поездку.",
      it: "Sicura di sé, colorata e piena di personalità, Little Joya® porta un tocco fresco e femminile in ogni viaggio.",
      hy: "Ինքնավստահ, գունեղ և բնավորությամբ՝ Little Joya®-ն յուրաքանչյուր ճանապարհին բերում է թարմ, կանացի շունչ։",
    },
  },
  {
    slug: "little-dog",
    sortOrder: 9,
    accent: "#7FCBF0",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 2900,
    page: 56,
    prefix: same("Little Dog"),
    name: same("Little Dog"),
    tagline: {
      en: "Your loyal companion for every journey.",
      ru: "Верный спутник в каждой поездке.",
      it: "Il tuo compagno fedele per ogni viaggio.",
      hy: "Ձեր հավատարիմ ուղեկիցը յուրաքանչյուր ճանապարհին։",
    },
    description: {
      en: "Playful, dependable and full of character, Little Dog® brings a friendly personality and premium fragrance to every drive.",
      ru: "Игривый, надёжный и с характером — Little Dog® дарит дружелюбное настроение и премиальный аромат в каждой поездке.",
      it: "Giocoso, affidabile e pieno di carattere, Little Dog® porta una personalità amichevole e una fragranza premium in ogni viaggio.",
      hy: "Խաղասեր, հուսալի և բնավորությամբ՝ Little Dog®-ը յուրաքանչյուր ճանապարհին բերում է ընկերական տրամադրություն և պրեմիում բույր։",
    },
  },
  {
    slug: "little-pup",
    sortOrder: 10,
    accent: "#8FA9E6",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 2900,
    page: 60,
    prefix: same("Little Pup"),
    name: same("Little Pup"),
    tagline: {
      en: "Small in size. Big on personality.",
      ru: "Маленький размер — большой характер.",
      it: "Piccolo di taglia. Grande di personalità.",
      hy: "Փոքր չափս՝ մեծ բնավորություն։",
    },
    description: {
      en: "The playful little companion that brings fragrance and fun to every drive — always ready for the next adventure.",
      ru: "Игривый маленький спутник, который приносит аромат и радость в каждую поездку и всегда готов к новым приключениям.",
      it: "Il piccolo compagno giocoso che porta fragranza e divertimento in ogni viaggio, sempre pronto per la prossima avventura.",
      hy: "Խաղասեր փոքրիկ ուղեկից, որը յուրաքանչյուր ճանապարհին բերում է բույր և ուրախություն ու միշտ պատրաստ է նոր արկածների։",
    },
  },
  {
    slug: "little-cat",
    sortOrder: 11,
    accent: "#A9D4F5",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 2900,
    page: 62,
    prefix: same("Little Cat"),
    name: same("Little Cat"),
    tagline: {
      en: "Curious by nature. Full of character.",
      ru: "Любопытный по натуре, с характером.",
      it: "Curioso per natura. Pieno di carattere.",
      hy: "Բնույթով հետաքրքրասեր, լի բնավորությամբ։",
    },
    description: {
      en: "The curious little character with a personality of its own — full of charm and a little mischief.",
      ru: "Любопытный маленький персонаж со своим характером — полон обаяния и лёгкого озорства.",
      it: "Il piccolo personaggio curioso con una personalità tutta sua, pieno di fascino e un pizzico di malizia.",
      hy: "Հետաքրքրասեր փոքրիկ կերպար՝ իր բնավորությամբ, հմայքով և մի քիչ չարաճճիությամբ։",
    },
  },
  {
    slug: "little-duck",
    sortOrder: 12,
    accent: "#FFD84D",
    hero: true,
    format: "VENT_CLIP",
    days45: true,
    demoPriceAmd: 2900,
    page: 64,
    prefix: same("Little Duck"),
    name: same("Little Duck"),
    tagline: {
      en: "Bright by nature. Full of fun.",
      ru: "Яркий по натуре, полон веселья.",
      it: "Solare per natura. Pieno di allegria.",
      hy: "Բնույթով պայծառ, լի ուրախությամբ։",
    },
    description: {
      en: "The cheerful character that brightens every journey — playful, colourful and full of fragrance.",
      ru: "Весёлый персонаж, который делает ярче каждую поездку: игривый, красочный и ароматный.",
      it: "Il personaggio allegro che illumina ogni viaggio: giocoso, colorato e ricco di fragranza.",
      hy: "Ուրախ կերպար, որը պայծառացնում է յուրաքանչյուր ճանապարհ․ խաղասեր, գունեղ և բուրավետ։",
    },
  },
  {
    slug: "bottle",
    sortOrder: 13,
    accent: "#9CCC65",
    hero: true,
    format: "BOTTLE",
    days45: true,
    demoPriceAmd: 3900,
    page: 34,
    prefix: same("Little Joe Bottle"),
    name: same("Little Joe Bottle"),
    tagline: {
      en: "A little icon. A new way to freshen.",
      ru: "Маленькая икона — новый способ освежить воздух.",
      it: "Una piccola icona. Un nuovo modo di profumare.",
      hy: "Փոքրիկ պատկերակ՝ թարմության նոր ձև։",
    },
    description: {
      en: "Distinctive design with long-lasting fragrance. Simply hang it from the rear-view mirror.",
      ru: "Узнаваемый дизайн и стойкий аромат. Просто повесьте на зеркало заднего вида.",
      it: "Design inconfondibile e fragranza duratura. Basta appenderlo allo specchietto retrovisore.",
      hy: "Ճանաչելի դիզայն և երկարատև բույր։ Պարզապես կախեք հետադիտման հայելուց։",
    },
  },
  {
    slug: "pump-spray",
    sortOrder: 14,
    accent: "#8FCBEF",
    hero: true,
    format: "OTHER",
    days45: false,
    demoPriceAmd: 4900,
    page: 36,
    prefix: same("Little Joe Pump Spray"),
    name: same("Little Joe Pump Spray"),
    tagline: {
      en: "Freshness. Just a spray away.",
      ru: "Свежесть — одним нажатием.",
      it: "Freschezza a portata di spruzzo.",
      hy: "Թարմությունը՝ մեկ ցողումով։",
    },
    description: {
      en: "Refresh your car or home in seconds. Natural essential oils in an alcohol-free, vegan-friendly formula.",
      ru: "Освежите салон или дом за секунды. Натуральные эфирные масла, формула без спирта, подходит веганам.",
      it: "Rinfresca auto o casa in pochi secondi. Oli essenziali naturali in una formula senza alcol e vegan-friendly.",
      hy: "Թարմացրեք մեքենան կամ տունը վայրկյանների ընթացքում։ Բնական եթերային յուղեր, առանց սպիրտի, վեգանների համար հարմար բանաձև։",
    },
  },
  {
    slug: "car-care",
    sortOrder: 15,
    accent: "#9DB4D3",
    hero: true,
    format: "OTHER",
    days45: false,
    demoPriceAmd: 5900,
    page: 38,
    prefix: same("Little Joe"),
    name: { hy: "Մեքենայի խնամք", ru: "Уход за автомобилем", it: "Cura dell'auto", en: "Car Care Range" },
    tagline: {
      en: "Made to clean. Designed to care.",
      ru: "Создано чистить. Создано заботиться.",
      it: "Fatto per pulire. Pensato per curare.",
      hy: "Ստեղծված է մաքրելու և խնամելու համար։",
    },
    description: {
      en: "From interior to exterior: effective cleaning and care with the distinctive personality of the Little Joe® brand.",
      ru: "От салона до кузова: эффективная чистка и уход с узнаваемым характером Little Joe®.",
      it: "Dall'interno all'esterno: pulizia e cura efficaci con la personalità inconfondibile di Little Joe®.",
      hy: "Սրահից մինչև թափք․ արդյունավետ մաքրում և խնամք՝ Little Joe®-ի ճանաչելի բնավորությամբ։",
    },
  },
  {
    slug: "wet-wipes",
    sortOrder: 16,
    accent: "#7FC4EF",
    hero: true,
    format: "OTHER",
    days45: false,
    demoPriceAmd: 2500,
    page: 40,
    prefix: same("Little Joe"),
    name: { hy: "Խոնավ անձեռոցիկներ", ru: "Влажные салфетки", it: "Salviette umidificate", en: "Wet Wipes" },
    tagline: {
      en: "Cleaning made easy. Wherever you go.",
      ru: "Чистота — легко и где угодно.",
      it: "Pulire è facile. Ovunque tu sia.",
      hy: "Մաքրությունը՝ հեշտ և ամենուր։",
    },
    description: {
      en: "Practical cleaning wipes for quick and easy car care — cockpit, leather, glass and multiple surfaces.",
      ru: "Практичные салфетки для быстрого ухода за автомобилем: торпедо, кожа, стёкла и другие поверхности.",
      it: "Salviette pratiche per una cura dell'auto rapida e semplice: cruscotto, pelle, vetri e superfici diverse.",
      hy: "Գործնական անձեռոցիկներ մեքենայի արագ խնամքի համար․ վահանակ, կաշի, ապակի և այլ մակերեսներ։",
    },
  },
  {
    slug: "paper",
    sortOrder: 17,
    accent: "#79C3F2",
    hero: true,
    format: "PAPER",
    days45: false,
    demoPriceAmd: 1200,
    page: 44,
    prefix: same("Little Joe Paper"),
    name: same("Little Joe Paper"),
    tagline: {
      en: "The iconic smile. Ready to hang.",
      ru: "Знаменитая улыбка — готова повиснуть.",
      it: "Il sorriso iconico. Pronto da appendere.",
      hy: "Հայտնի ժպիտը՝ պատրաստ կախվելու։",
    },
    description: {
      en: "A simple and colourful way to bring Little Joe® fragrance into your car. Just hang it from the rear-view mirror.",
      ru: "Простой и яркий способ принести аромат Little Joe® в автомобиль. Просто повесьте на зеркало заднего вида.",
      it: "Un modo semplice e colorato per portare la fragranza Little Joe® in auto. Basta appenderlo allo specchietto.",
      hy: "Little Joe® բույրը մեքենա բերելու պարզ և գունեղ միջոց։ Պարզապես կախեք հետադիտման հայելուց։",
    },
  },
  {
    slug: "triopack",
    sortOrder: 18,
    accent: "#5FB4EC",
    hero: true,
    format: "PAPER",
    days45: false,
    demoPriceAmd: 2900,
    page: 46,
    prefix: same("Little Joe Paper Triopack"),
    name: same("Little Joe Paper Triopack"),
    tagline: {
      en: "Three times the smile.",
      ru: "Втрое больше улыбок.",
      it: "Tre volte il sorriso.",
      hy: "Եռակի ժպիտ։",
    },
    description: {
      en: "Three Little Joe® Paper air fresheners in one pack, with different designs and your favourite fragrance.",
      ru: "Три бумажных ароматизатора Little Joe® Paper в одной упаковке: разные дизайны и любимый аромат.",
      it: "Tre deodoranti Little Joe® Paper in una confezione, con design diversi e la tua fragranza preferita.",
      hy: "Երեք Little Joe® Paper բուրավետիչ մեկ փաթեթում՝ տարբեր դիզայնով և ձեր սիրելի բույրով։",
    },
  },
  {
    slug: "scented-card",
    sortOrder: 19,
    accent: "#C7B3E3",
    hero: true,
    format: "HANGING",
    days45: false,
    demoPriceAmd: 1500,
    page: 48,
    prefix: same("Little Joe Scented Card"),
    name: same("Little Joe Scented Card"),
    tagline: {
      en: "Freshness. Wherever you need it.",
      ru: "Свежесть там, где она нужна.",
      it: "Freschezza, ovunque serva.",
      hy: "Թարմություն՝ որտեղ պետք է։",
    },
    description: {
      en: "A versatile air freshener for your car, home or office. Simply hang it wherever you want a fresh, pleasant scent.",
      ru: "Универсальный ароматизатор для машины, дома или офиса. Повесьте туда, где хочется свежести.",
      it: "Un deodorante versatile per auto, casa o ufficio. Appendilo dove desideri un profumo fresco e piacevole.",
      hy: "Բազմակողմանի բուրավետիչ մեքենայի, տան կամ գրասենյակի համար։ Կախեք այնտեղ, որտեղ թարմություն եք ուզում։",
    },
  },
  {
    slug: "scented-band",
    sortOrder: 20,
    accent: "#F28C28",
    hero: true,
    format: "OTHER",
    days45: false,
    demoPriceAmd: 2500,
    page: 50,
    prefix: same("Little Joe Scented Band"),
    name: same("Little Joe Scented Band"),
    tagline: {
      en: "Citronella. Made to wear.",
      ru: "Цитронелла, которую можно носить.",
      it: "Citronella da indossare.",
      hy: "Ցիտրոնելլա, որը կարելի է կրել։",
    },
    description: {
      en: "A practical scented bracelet infused with the fresh fragrance of citronella, in two sizes for kids and adults.",
      ru: "Практичный браслет с свежим ароматом цитронеллы, в двух размерах — для детей и взрослых.",
      it: "Un pratico braccialetto profumato alla citronella, in due misure per bambini e adulti.",
      hy: "Գործնական բուրավետ ապարանջան՝ ցիտրոնելլայի թարմ բույրով, երկու չափսով՝ երեխաների և մեծահասակների համար։",
    },
  },
  {
    slug: "tumble-fresh",
    sortOrder: 21,
    accent: "#D98CC1",
    hero: true,
    format: "OTHER",
    days45: false,
    demoPriceAmd: 3500,
    page: 72,
    prefix: same("Tumble Fresh"),
    name: same("Tumble Fresh"),
    tagline: {
      en: "Freshness that lasts beyond the dryer.",
      ru: "Свежесть, которая остаётся после сушки.",
      it: "Freschezza che dura oltre l'asciugatrice.",
      hy: "Թարմություն, որը մնում է չորացումից հետո։",
    },
    description: {
      en: "A laundry fragrance booster for tumble dryers. Each Tumble Fresh® can be used for up to 15 drying cycles.",
      ru: "Ароматизатор белья для сушильных машин. Каждый Tumble Fresh® рассчитан до 15 циклов сушки.",
      it: "Un profumatore per bucato da usare in asciugatrice. Ogni Tumble Fresh® dura fino a 15 cicli di asciugatura.",
      hy: "Լվացքի բուրավետիչ չորանոց մեքենաների համար։ Յուրաքանչյուր Tumble Fresh® բավական է մինչև 15 չորացման ցիկլի։",
    },
  },
  {
    slug: "at-work",
    sortOrder: 22,
    accent: "#6FB8EC",
    hero: true,
    format: "OTHER",
    days45: false,
    demoPriceAmd: 1500,
    page: 74,
    prefix: same("Little Joe At Work!"),
    name: same("Little Joe At Work!"),
    tagline: {
      en: "Bring a little personality to your workspace.",
      ru: "Немного характера для рабочего стола.",
      it: "Un tocco di personalità alla tua scrivania.",
      hy: "Մի փոքր բնավորություն ձեր աշխատասեղանին։",
    },
    description: {
      en: "Everyday office essentials with Little Joe®'s unmistakable character — practical, playful and colourful.",
      ru: "Повседневные канцтовары с узнаваемым характером Little Joe® — практичные, игривые и яркие.",
      it: "Articoli da ufficio quotidiani con l'inconfondibile carattere di Little Joe®: pratici, giocosi e colorati.",
      hy: "Ամենօրյա գրենական պիտույքներ՝ Little Joe®-ի ճանաչելի բնավորությամբ․ գործնական, խաղային և գունեղ։",
    },
  },
  {
    slug: "merchandise",
    sortOrder: 23,
    accent: "#1E88E5",
    hero: false,
    format: "OTHER",
    days45: false,
    demoPriceAmd: 6500,
    page: 78,
    prefix: same("Little Joe"),
    name: { hy: "Բրենդային ապրանքներ", ru: "Фирменные товары", it: "Merchandising", en: "Merchandise" },
    tagline: {
      en: "Little Joe® beyond the car.",
      ru: "Little Joe® не только в машине.",
      it: "Little Joe® oltre l'auto.",
      hy: "Little Joe®-ն ոչ միայն մեքենայում։",
    },
    description: {
      en: "T-shirts and bath bombs with the Little Joe® smile.",
      ru: "Футболки и бомбочки для ванны с улыбкой Little Joe®.",
      it: "T-shirt e bombe da bagno con il sorriso di Little Joe®.",
      hy: "Շապիկներ և լոգանքի գնդիկներ՝ Little Joe®-ի ժպիտով։",
    },
  },
];
