// GENERATED from the brand book PDF (see brandbook-lines.ts): one entry per
// packshot that carries an article number and EAN. Do not edit by hand —
// regenerate. `scent` is the manufacturer's scent name (kept as printed);
// `label` localises non-scent item names. `family` is the SHOP'S taxonomy,
// assigned only where the scent name itself names the note (e.g. "Vanilla").

import type { Locale } from '../../src/generated/prisma/enums';

export type Item = {
  line: string;
  slug: string;
  art: string;
  ean: string;
  image: string;
  w: number;
  h: number;
  scent: string | null;
  label: Record<Locale, string> | null;
  family: string | null;
  dims: string | null;
  price: number | null;
};

export const ITEMS: Item[] = [
  {
    line: 'little-joe',
    slug: 'little-joe-vanilla',
    art: 'EF0101',
    ean: '7640125380101',
    image: 'ef0101.webp',
    w: 205,
    h: 344,
    scent: 'Vanilla',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-cashmere',
    art: 'EF1616',
    ean: '7640186841696',
    image: 'ef1616.webp',
    w: 205,
    h: 344,
    scent: 'Cashmere',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-black-velvet',
    art: 'EF0606',
    ean: '7640125380156',
    image: 'ef0606.webp',
    w: 205,
    h: 344,
    scent: 'Black Velvet',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-new-car',
    art: 'EF0202',
    ean: '7640125380118',
    image: 'ef0202.webp',
    w: 205,
    h: 344,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-ginger-lemon',
    art: 'EF1717',
    ean: '7640186841092',
    image: 'ef1717.webp',
    w: 205,
    h: 344,
    scent: 'Ginger Lemon',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-ocean-splash',
    art: 'EF0707',
    ean: '7640125380163',
    image: 'ef0707.webp',
    w: 205,
    h: 344,
    scent: 'Ocean Splash',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-passion',
    art: 'EF0303',
    ean: '7640125380125',
    image: 'ef0303.webp',
    w: 205,
    h: 344,
    scent: 'Passion',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-fresh-mint',
    art: 'EF0808',
    ean: '7640125380170',
    image: 'ef0808.webp',
    w: 205,
    h: 344,
    scent: 'Fresh Mint',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-cherry',
    art: 'EF0404',
    ean: '7640125380132',
    image: 'ef0404.webp',
    w: 205,
    h: 344,
    scent: 'Cherry',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-cedarwood',
    art: 'EF1919',
    ean: '7640186841108',
    image: 'ef1919.webp',
    w: 205,
    h: 344,
    scent: 'Cedarwood',
    label: null,
    family: 'woody',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-fruit',
    art: 'EF0909',
    ean: '7640186840415',
    image: 'ef0909.webp',
    w: 205,
    h: 344,
    scent: 'Fruit',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-tonic',
    art: 'EF1010',
    ean: '7640186840422',
    image: 'ef1010.webp',
    w: 205,
    h: 344,
    scent: 'Tonic',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-flower',
    art: 'EF1313',
    ean: '7640186840576',
    image: 'ef1313.webp',
    w: 205,
    h: 344,
    scent: 'Flower',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-pina-colada',
    art: 'EF1414',
    ean: '7640186841320',
    image: 'ef1414.webp',
    w: 205,
    h: 344,
    scent: 'Piña Colada',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-odour-neutraliser',
    art: 'EF1515',
    ean: '7640186841719',
    image: 'ef1515.webp',
    w: 205,
    h: 344,
    scent: 'Odour Neutraliser',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-bubble-gum',
    art: 'EF2939',
    ean: '7640186842488',
    image: 'ef2939.webp',
    w: 205,
    h: 344,
    scent: 'Bubble Gum',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-apple',
    art: 'EF3243',
    ean: '7640186842563',
    image: 'ef3243.webp',
    w: 205,
    h: 344,
    scent: 'Apple',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-cappuccino',
    art: 'EF3963',
    ean: '7640186843683',
    image: 'ef3963.webp',
    w: 205,
    h: 336,
    scent: 'Cappuccino',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-sport',
    art: 'EF4170',
    ean: '7640186846028',
    image: 'ef4170.webp',
    w: 205,
    h: 344,
    scent: 'Sport',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-litchi-rose',
    art: 'EF4271',
    ean: '7640186846035',
    image: 'ef4271.webp',
    w: 205,
    h: 344,
    scent: 'Litchi Rose',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-white-blossom',
    art: 'EF0273',
    ean: '7640186846059',
    image: 'ef0273.webp',
    w: 205,
    h: 344,
    scent: 'White Blossom',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-wild-strawberry',
    art: 'EF1172',
    ean: '7640186846042',
    image: 'ef1172.webp',
    w: 205,
    h: 344,
    scent: 'Wild Strawberry',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-joe',
    slug: 'little-joe-elegant',
    art: 'EF1869',
    ean: '7640186846011',
    image: 'ef1869.webp',
    w: 205,
    h: 344,
    scent: 'Elegant',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-vanilla',
    art: 'ET0101',
    ean: '7640186840019',
    image: 'et0101.webp',
    w: 205,
    h: 344,
    scent: 'Vanilla',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-new-car',
    art: 'ET0202',
    ean: '7640186840026',
    image: 'et0202.webp',
    w: 205,
    h: 344,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-passion',
    art: 'ET0303',
    ean: '7640186841948',
    image: 'et0303.webp',
    w: 205,
    h: 344,
    scent: 'Passion',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-cherry',
    art: 'ET0404',
    ean: '7640186840460',
    image: 'et0404.webp',
    w: 205,
    h: 344,
    scent: 'Cherry',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-flower',
    art: 'ET1313',
    ean: '7640186840033',
    image: 'et1313.webp',
    w: 205,
    h: 344,
    scent: 'Flower',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-pina-colada',
    art: 'ET1414',
    ean: '7640186841962',
    image: 'et1414.webp',
    w: 205,
    h: 344,
    scent: 'Piña Colada',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-cashmere',
    art: 'ET1616',
    ean: '7640186842075',
    image: 'et1616.webp',
    w: 205,
    h: 344,
    scent: 'Cashmere',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-bubble-gum',
    art: 'ET2939',
    ean: '7640186842501',
    image: 'et2939.webp',
    w: 206,
    h: 346,
    scent: 'Bubble Gum',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-ginger-lemon',
    art: 'ET1717',
    ean: '7640186842082',
    image: 'et1717.webp',
    w: 205,
    h: 344,
    scent: 'Ginger Lemon',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-cedarwood',
    art: 'ET1919',
    ean: '7640186842099',
    image: 'et1919.webp',
    w: 205,
    h: 344,
    scent: 'Cedarwood',
    label: null,
    family: 'woody',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-black-velvet',
    art: 'ET0606',
    ean: '7640186840057',
    image: 'et0606.webp',
    w: 205,
    h: 344,
    scent: 'Black Velvet',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-ocean-splash',
    art: 'ET0707',
    ean: '7640186840040',
    image: 'et0707.webp',
    w: 205,
    h: 344,
    scent: 'Ocean Splash',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-fresh-mint',
    art: 'ET0808',
    ean: '7640186840064',
    image: 'et0808.webp',
    w: 205,
    h: 344,
    scent: 'Fresh Mint',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-fruit',
    art: 'ET0909',
    ean: '7640186840453',
    image: 'et0909.webp',
    w: 205,
    h: 344,
    scent: 'Fruit',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-tonic',
    art: 'ET1010',
    ean: '7640186841917',
    image: 'et1010.webp',
    w: 205,
    h: 344,
    scent: 'Tonic',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-apple',
    art: 'ET3243',
    ean: '7640186842587',
    image: 'et3243.webp',
    w: 206,
    h: 346,
    scent: 'Apple',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'thumbs-up',
    slug: 'thumbs-up-cappuccino',
    art: 'ET3963',
    ean: '7640186843706',
    image: 'et3963.webp',
    w: 205,
    h: 344,
    scent: 'Cappuccino',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'winter-edition',
    slug: 'winter-edition-holiday-sparkle',
    art: 'EF1655',
    ean: '7640186843188',
    image: 'ef1655.webp',
    w: 235,
    h: 369,
    scent: 'Holiday Sparkle',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'winter-edition',
    slug: 'winter-edition-frosty-delight',
    art: 'EF1754',
    ean: '7640186843171',
    image: 'ef1754.webp',
    w: 235,
    h: 369,
    scent: 'Frosty Delight',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'winter-edition',
    slug: 'winter-edition-apple-cinnamon-treat',
    art: 'EF0453',
    ean: '7640186843164',
    image: 'ef0453.webp',
    w: 235,
    h: 369,
    scent: 'Apple Cinnamon Treat',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'winter-edition',
    slug: 'winter-edition-fresh-pine',
    art: 'EF3456',
    ean: '7640186843195',
    image: 'ef3456.webp',
    w: 235,
    h: 369,
    scent: 'Fresh Pine',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'best-mom-dad',
    slug: 'best-mom-dad-best-mom',
    art: 'LO1216',
    ean: '7640186845366',
    image: 'lo1216.webp',
    w: 271,
    h: 457,
    scent: null,
    label: {
      hy: 'Լավագույն մայրիկ',
      ru: 'Лучшая мама',
      it: 'Migliore mamma',
      en: 'Best Mom',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'best-mom-dad',
    slug: 'best-mom-dad-best-dad',
    art: 'EF1016',
    ean: '7640186845373',
    image: 'ef1016.webp',
    w: 271,
    h: 459,
    scent: null,
    label: {
      hy: 'Լավագույն հայրիկ',
      ru: 'Лучший папа',
      it: 'Miglior papà',
      en: 'Best Dad',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'i-love',
    slug: 'i-love-i-love-you',
    art: 'LO2601',
    ean: '7640125380828',
    image: 'lo2601.webp',
    w: 204,
    h: 328,
    scent: null,
    label: {
      hy: 'I ♥ You',
      ru: 'I ♥ You',
      it: 'I ♥ You',
      en: 'I ♥ You',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-i-love-soccer-new-car-blue',
    art: 'SJ0702',
    ean: '7640186840750',
    image: 'sj0702.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'I ♥ Soccer New Car, կապույտ',
      ru: 'I ♥ Soccer New Car, синий',
      it: 'I ♥ Soccer New Car, blu',
      en: 'I ♥ Soccer New Car, blue',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-i-love-soccer-new-car-red',
    art: 'SJ0402',
    ean: '7640186840743',
    image: 'sj0402.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'I ♥ Soccer New Car, կարմիր',
      ru: 'I ♥ Soccer New Car, красный',
      it: 'I ♥ Soccer New Car, rosso',
      en: 'I ♥ Soccer New Car, red',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-georgia',
    art: 'SJ0202',
    ean: '7640186843119',
    image: 'sj0202.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Վրաստան',
      ru: 'Грузия',
      it: 'Georgia',
      en: 'Georgia',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-slovenia',
    art: 'SJ0705',
    ean: '7640186843089',
    image: 'sj0705.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Սլովենիա',
      ru: 'Словения',
      it: 'Slovenia',
      en: 'Slovenia',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-slovakia',
    art: 'SJ0703',
    ean: '7640186842983',
    image: 'sj0703.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Սլովակիա',
      ru: 'Словакия',
      it: 'Slovacchia',
      en: 'Slovakia',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-switzerland',
    art: 'SJ0404',
    ean: '7640186842938',
    image: 'sj0404.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Շվեյցարիա',
      ru: 'Швейцария',
      it: 'Svizzera',
      en: 'Switzerland',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-serbia',
    art: 'SJ0409',
    ean: '7640186843003',
    image: 'sj0409.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Սերբիա',
      ru: 'Сербия',
      it: 'Serbia',
      en: 'Serbia',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-spain',
    art: 'SJ0407',
    ean: '7640186842945',
    image: 'sj0407.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Իսպանիա',
      ru: 'Испания',
      it: 'Spagna',
      en: 'Spain',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-romania',
    art: 'SJ0101',
    ean: '7640186843065',
    image: 'sj0101.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Ռումինիա',
      ru: 'Румыния',
      it: 'Romania',
      en: 'Romania',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-portugal',
    art: 'SJ0411',
    ean: '7640186843058',
    image: 'sj0411.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Պորտուգալիա',
      ru: 'Португалия',
      it: 'Portogallo',
      en: 'Portugal',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-germany',
    art: 'SJ0401',
    ean: '7640186842914',
    image: 'sj0401.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Գերմանիա',
      ru: 'Германия',
      it: 'Germania',
      en: 'Germany',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-czech-republic',
    art: 'SJ0412',
    ean: '7640186843072',
    image: 'sj0412.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Չեխիա',
      ru: 'Чехия',
      it: 'Repubblica Ceca',
      en: 'Czech Republic',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-france',
    art: 'SJ0704',
    ean: '7640186843034',
    image: 'sj0704.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Ֆրանսիա',
      ru: 'Франция',
      it: 'Francia',
      en: 'France',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-netherlands',
    art: 'SJ0901',
    ean: '7640186843027',
    image: 'sj0901.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Նիդեռլանդներ',
      ru: 'Нидерланды',
      it: 'Paesi Bassi',
      en: 'Netherlands',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-croatia',
    art: 'SJ0408',
    ean: '7640186842952',
    image: 'sj0408.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Խորվաթիա',
      ru: 'Хорватия',
      it: 'Croazia',
      en: 'Croatia',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-england',
    art: 'SJ0201',
    ean: '7640186843010',
    image: 'sj0201.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Անգլիա',
      ru: 'Англия',
      it: 'Inghilterra',
      en: 'England',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-italy',
    art: 'SJ0701',
    ean: '7640186842969',
    image: 'sj0701.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Իտալիա',
      ru: 'Италия',
      it: 'Italia',
      en: 'Italy',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-belgium',
    art: 'SJ0410',
    ean: '7640186843041',
    image: 'sj0410.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Բելգիա',
      ru: 'Бельгия',
      it: 'Belgio',
      en: 'Belgium',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-denmark',
    art: 'SJ0406',
    ean: '7640186842990',
    image: 'sj0406.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Դանիա',
      ru: 'Дания',
      it: 'Danimarca',
      en: 'Denmark',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-hungary',
    art: 'SJ0403',
    ean: '7640186842921',
    image: 'sj0403.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Հունգարիա',
      ru: 'Венгрия',
      it: 'Ungheria',
      en: 'Hungary',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'soccer',
    slug: 'soccer-albania',
    art: 'SJ0405',
    ean: '7640186842976',
    image: 'sj0405.webp',
    w: 222,
    h: 368,
    scent: null,
    label: {
      hy: 'Ալբանիա',
      ru: 'Албания',
      it: 'Albania',
      en: 'Albania',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'love-edition',
    slug: 'love-edition-candy-kisses',
    art: 'LE3620',
    ean: '7640186843652',
    image: 'le3620.webp',
    w: 224,
    h: 384,
    scent: 'Candy Kisses',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'love-edition',
    slug: 'love-edition-sweet-berry-dreams',
    art: 'LE3739',
    ean: '7640186843669',
    image: 'le3739.webp',
    w: 244,
    h: 410,
    scent: 'Sweet Berry Dreams',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'love-edition',
    slug: 'love-edition-sunshine-bliss',
    art: 'LE3801',
    ean: '7640186843676',
    image: 'le3801.webp',
    w: 224,
    h: 384,
    scent: 'Sunshine Bliss',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'bottle',
    slug: 'bottle-bamboo',
    art: 'BJ0851',
    ean: '7640186842655',
    image: 'bj0851.webp',
    w: 224,
    h: 360,
    scent: 'Bamboo',
    label: null,
    family: 'woody',
    dims: null,
    price: null,
  },
  {
    line: 'bottle',
    slug: 'bottle-flower',
    art: 'BJ1313',
    ean: '7640186842648',
    image: 'bj1313.webp',
    w: 224,
    h: 360,
    scent: 'Flower',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'bottle',
    slug: 'bottle-bubble-gum',
    art: 'BJ2939',
    ean: '7640186845328',
    image: 'bj2939.webp',
    w: 232,
    h: 378,
    scent: 'Bubble Gum',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'bottle',
    slug: 'bottle-vanilla',
    art: 'BJ0101',
    ean: '7640186842624',
    image: 'bj0101.webp',
    w: 224,
    h: 360,
    scent: 'Vanilla',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'bottle',
    slug: 'bottle-black-velvet',
    art: 'BJ0606',
    ean: '7640186845335',
    image: 'bj0606.webp',
    w: 232,
    h: 378,
    scent: 'Black Velvet',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'bottle',
    slug: 'bottle-new-car',
    art: 'BJ0202',
    ean: '7640186842631',
    image: 'bj0202.webp',
    w: 224,
    h: 360,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'bottle',
    slug: 'bottle-exotic-fruit',
    art: 'BJ0909',
    ean: '7640186845342',
    image: 'bj0909.webp',
    w: 232,
    h: 378,
    scent: 'Exotic Fruit',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'pump-spray',
    slug: 'pump-spray-vital-energy',
    art: 'JS0859',
    ean: '7640186843386',
    image: 'js0859.webp',
    w: 160,
    h: 352,
    scent: 'Vital Energy',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'pump-spray',
    slug: 'pump-spray-tropical-scents',
    art: 'JS0962',
    ean: '7640186843416',
    image: 'js0962.webp',
    w: 160,
    h: 352,
    scent: 'Tropical Scents',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'pump-spray',
    slug: 'pump-spray-fresh-start',
    art: 'JS1057',
    ean: '7640186843362',
    image: 'js1057.webp',
    w: 160,
    h: 352,
    scent: 'Fresh Start',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'pump-spray',
    slug: 'pump-spray-absolutely-fabulous',
    art: 'JS1360',
    ean: '7640186843393',
    image: 'js1360.webp',
    w: 160,
    h: 359,
    scent: 'Absolutely Fabulous',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'pump-spray',
    slug: 'pump-spray-spice-fusion',
    art: 'JS0458',
    ean: '7640186843379',
    image: 'js0458.webp',
    w: 160,
    h: 352,
    scent: 'Spice Fusion',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'pump-spray',
    slug: 'pump-spray-vanilla-blossom',
    art: 'JS0161',
    ean: '7640186843409',
    image: 'js0161.webp',
    w: 160,
    h: 352,
    scent: 'Vanilla Blossom',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'car-care',
    slug: 'car-care-interior-cleaner-new-car',
    art: 'CR04',
    ean: '7640186845281',
    image: 'cr04.webp',
    w: 208,
    h: 432,
    scent: null,
    label: {
      hy: 'Սրահի մաքրիչ · New Car',
      ru: 'Очиститель салона · New Car',
      it: 'Detergente interni · New Car',
      en: 'Interior Cleaner · New Car',
    },
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'car-care',
    slug: 'car-care-glass-cleaner-tropical-fresh',
    art: 'CR03',
    ean: '7640186845274',
    image: 'cr03.webp',
    w: 208,
    h: 432,
    scent: null,
    label: {
      hy: 'Ապակու մաքրիչ · Tropical Fresh',
      ru: 'Очиститель стёкол · Tropical Fresh',
      it: 'Detergente vetri · Tropical Fresh',
      en: 'Glass Cleaner · Tropical Fresh',
    },
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'car-care',
    slug: 'car-care-wheel-cleaner-lemon',
    art: 'CR01',
    ean: '7640186845250',
    image: 'cr01.webp',
    w: 208,
    h: 432,
    scent: null,
    label: {
      hy: 'Անվահեծերի մաքրիչ · Lemon',
      ru: 'Очиститель дисков · Lemon',
      it: 'Detergente cerchi · Lemon',
      en: 'Wheel Cleaner · Lemon',
    },
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'car-care',
    slug: 'car-care-upholstery-cleaner-ocean-splash',
    art: 'CR05',
    ean: '7640186845298',
    image: 'cr05.webp',
    w: 208,
    h: 424,
    scent: null,
    label: {
      hy: 'Պաստառի մաքրիչ · Ocean Splash',
      ru: 'Очиститель обивки · Ocean Splash',
      it: 'Detergente tappezzeria · Ocean Splash',
      en: 'Upholstery Cleaner · Ocean Splash',
    },
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'car-care',
    slug: 'car-care-tyre-shine-high-gloss-finish',
    art: 'CR02',
    ean: '7640186845267',
    image: 'cr02.webp',
    w: 208,
    h: 432,
    scent: null,
    label: {
      hy: 'Անվադողերի փայլ · բարձր փայլ',
      ru: 'Блеск для шин · глянец',
      it: 'Lucida gomme · effetto lucido',
      en: 'Tyre Shine · High Gloss Finish',
    },
    family: null,
    dims: null,
    price: 5500,
  },
  {
    line: 'car-care',
    slug: 'car-care-cockpit-spray-black-velvet',
    art: 'CR06',
    ean: '7640186845304',
    image: 'cr06.webp',
    w: 208,
    h: 432,
    scent: null,
    label: {
      hy: 'Վահանակի սփրեյ · Black Velvet',
      ru: 'Спрей для торпедо · Black Velvet',
      it: 'Spray cruscotto · Black Velvet',
      en: 'Cockpit Spray · Black Velvet',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'wet-wipes',
    slug: 'wet-wipes-wet-wipes-cockpit',
    art: 'LW0404',
    ean: '7640186845816',
    image: 'lw0404.webp',
    w: 390,
    h: 424,
    scent: null,
    label: {
      hy: 'Խոնավ անձեռոցիկներ վահանակի համար',
      ru: 'Влажные салфетки для торпедо',
      it: 'Salviette per cruscotto',
      en: 'Wet Wipes · Cockpit',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'wet-wipes',
    slug: 'wet-wipes-wet-wipes-leather-care',
    art: 'LW0202',
    ean: '7640186845793',
    image: 'lw0202.webp',
    w: 368,
    h: 400,
    scent: null,
    label: {
      hy: 'Խոնավ անձեռոցիկներ կաշվի համար',
      ru: 'Влажные салфетки для кожи',
      it: 'Salviette per pelle',
      en: 'Wet Wipes · Leather Care',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'wet-wipes',
    slug: 'wet-wipes-wet-wipes-glass-and-screen',
    art: 'LW0303',
    ean: '7640186845809',
    image: 'lw0303.webp',
    w: 390,
    h: 424,
    scent: null,
    label: {
      hy: 'Խոնավ անձեռոցիկներ ապակու և էկրանի համար',
      ru: 'Влажные салфетки для стёкол и экранов',
      it: 'Salviette per vetri e schermi',
      en: 'Wet Wipes · Glass & Screen',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'wet-wipes',
    slug: 'wet-wipes-wet-wipes-universal-cleaner',
    art: 'LW0101',
    ean: '7640186845489',
    image: 'lw0101.webp',
    w: 390,
    h: 424,
    scent: null,
    label: {
      hy: 'Ունիվերսալ խոնավ անձեռոցիկներ',
      ru: 'Универсальные влажные салфетки',
      it: 'Salviette universali',
      en: 'Wet Wipes · Universal Cleaner',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'paper',
    slug: 'paper-vanilla',
    art: 'CP0101',
    ean: '5450188580019',
    image: 'cp0101.webp',
    w: 197,
    h: 425,
    scent: 'Vanilla',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'paper',
    slug: 'paper-fresh-linen',
    art: 'CP1049',
    ean: '7640186844741',
    image: 'cp1049.webp',
    w: 197,
    h: 425,
    scent: 'Fresh Linen',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'paper',
    slug: 'paper-new-car',
    art: 'CP2002',
    ean: '5450188580026',
    image: 'cp2002.webp',
    w: 197,
    h: 425,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'paper',
    slug: 'paper-cherry',
    art: 'CP0404',
    ean: '5450188580071',
    image: 'cp0404.webp',
    w: 197,
    h: 425,
    scent: 'Cherry',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'paper',
    slug: 'paper-bubble-gum',
    art: 'CP2939',
    ean: '7640186844772',
    image: 'cp2939.webp',
    w: 197,
    h: 425,
    scent: 'Bubble Gum',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'paper',
    slug: 'paper-black-velvet',
    art: 'CP0606',
    ean: '5450188580088',
    image: 'cp0606.webp',
    w: 197,
    h: 425,
    scent: 'Black Velvet',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'paper',
    slug: 'paper-cashmere',
    art: 'CP1616',
    ean: '7640186844758',
    image: 'cp1616.webp',
    w: 197,
    h: 425,
    scent: 'Cashmere',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'triopack',
    slug: 'triopack-vanilla',
    art: 'CT0101',
    ean: '7640186845373',
    image: 'ct0101.webp',
    w: 197,
    h: 425,
    scent: 'Vanilla',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'triopack',
    slug: 'triopack-fresh-linen',
    art: 'CT1049',
    ean: '7640186845403',
    image: 'ct1049.webp',
    w: 197,
    h: 425,
    scent: 'Fresh Linen',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'triopack',
    slug: 'triopack-new-car',
    art: 'CT2002',
    ean: '7640186845427',
    image: 'ct2002.webp',
    w: 197,
    h: 425,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'triopack',
    slug: 'triopack-cherry',
    art: 'CT0404',
    ean: '7640186845380',
    image: 'ct0404.webp',
    w: 197,
    h: 425,
    scent: 'Cherry',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'triopack',
    slug: 'triopack-bubble-gum',
    art: 'CT2939',
    ean: '7640186845434',
    image: 'ct2939.webp',
    w: 197,
    h: 425,
    scent: 'Bubble Gum',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'triopack',
    slug: 'triopack-black-velvet',
    art: 'CT0606',
    ean: '7640186845397',
    image: 'ct0606.webp',
    w: 197,
    h: 425,
    scent: 'Black Velvet',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'triopack',
    slug: 'triopack-cashmere',
    art: 'CT1616',
    ean: '7640186845410',
    image: 'ct1616.webp',
    w: 197,
    h: 425,
    scent: 'Cashmere',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'scented-card',
    slug: 'scented-card-new-car',
    art: 'SC0223',
    ean: '7640186841535',
    image: 'sc0223.webp',
    w: 198,
    h: 426,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'scented-card',
    slug: 'scented-card-lavender',
    art: 'SC2424',
    ean: '7640186841566',
    image: 'sc2424.webp',
    w: 198,
    h: 426,
    scent: 'Lavender',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'scented-card',
    slug: 'scented-card-odour-neutraliser',
    art: 'SC1515',
    ean: '7640186841573',
    image: 'sc1515.webp',
    w: 198,
    h: 426,
    scent: 'Odour Neutraliser',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'scented-card',
    slug: 'scented-card-cherry',
    art: 'SC2304',
    ean: '7640186841559',
    image: 'sc2304.webp',
    w: 198,
    h: 426,
    scent: 'Cherry',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'scented-card',
    slug: 'scented-card-fresh-mint',
    art: 'SC2508',
    ean: '7640186841580',
    image: 'sc2508.webp',
    w: 198,
    h: 426,
    scent: 'Fresh Mint',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'scented-card',
    slug: 'scented-card-vanilla',
    art: 'SC2201',
    ean: '7640186841528',
    image: 'sc2201.webp',
    w: 198,
    h: 426,
    scent: 'Vanilla',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'scented-band',
    slug: 'scented-band-citronella-small-kids-blue',
    art: 'SB1032',
    ean: '7640186840606',
    image: 'sb1032.webp',
    w: 168,
    h: 88,
    scent: null,
    label: {
      hy: 'Ցիտրոնելլա, փոքր, երեխաների, կապույտ',
      ru: 'Цитронелла, маленький, детский, синий',
      it: 'Citronella, small, bambini, blu',
      en: 'Citronella · Small · Kids, blue',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'scented-band',
    slug: 'scented-band-citronella-small-kids-pink',
    art: 'SB2832',
    ean: '7640186840613',
    image: 'sb2832.webp',
    w: 168,
    h: 88,
    scent: null,
    label: {
      hy: 'Ցիտրոնելլա, փոքր, երեխաների, վարդագույն',
      ru: 'Цитронелла, маленький, детский, розовый',
      it: 'Citronella, small, bambini, rosa',
      en: 'Citronella · Small · Kids, pink',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'scented-band',
    slug: 'scented-band-citronella-large-adults-white',
    art: 'SB0232',
    ean: '7640186840620',
    image: 'sb0232.webp',
    w: 339,
    h: 178,
    scent: null,
    label: {
      hy: 'Ցիտրոնելլա, մեծ, մեծահասակների, սպիտակ',
      ru: 'Цитронелла, большой, взрослый, белый',
      it: 'Citronella, large, adulti, bianco',
      en: 'Citronella · Large · Adults, white',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'scented-band',
    slug: 'scented-band-citronella-large-adults-anthracite',
    art: 'SB1832',
    ean: '7640186840637',
    image: 'sb1832.webp',
    w: 168,
    h: 94,
    scent: null,
    label: {
      hy: 'Ցիտրոնելլա, մեծ, մեծահասակների, անտրացիտ',
      ru: 'Цитронелла, большой, взрослый, антрацит',
      it: 'Citronella, large, adulti, antracite',
      en: 'Citronella · Large · Adults, anthracite',
    },
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-joya',
    slug: 'little-joya-cotton-candy',
    art: 'EY3311',
    ean: '7640125380217',
    image: 'ey3311.webp',
    w: 248,
    h: 413,
    scent: 'Cotton Candy',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'little-joya',
    slug: 'little-joya-blueberry-slush',
    art: 'EY2939',
    ean: '7640186842808',
    image: 'ey2939.webp',
    w: 248,
    h: 407,
    scent: 'Blueberry Slush',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-joya',
    slug: 'little-joya-springtime',
    art: 'EY1213',
    ean: '7640186842815',
    image: 'ey1213.webp',
    w: 248,
    h: 408,
    scent: 'Springtime',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'little-joya',
    slug: 'little-joya-sweet-dreams',
    art: 'EY2409',
    ean: '7640186842822',
    image: 'ey2409.webp',
    w: 248,
    h: 407,
    scent: 'Sweet Dreams',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-joya',
    slug: 'little-joya-vanilla-cream',
    art: 'EY1401',
    ean: '7640125380224',
    image: 'ey1401.webp',
    w: 248,
    h: 408,
    scent: 'Vanilla Cream',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'little-joya',
    slug: 'little-joya-new-car',
    art: 'EY0202',
    ean: '7640186840583',
    image: 'ey0202.webp',
    w: 248,
    h: 408,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-black-velvet',
    art: 'ED0606',
    ean: '7640125380354',
    image: 'ed0606.webp',
    w: 228,
    h: 382,
    scent: 'Black Velvet',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-fresh-mint',
    art: 'ED0808',
    ean: '7640186840484',
    image: 'ed0808.webp',
    w: 228,
    h: 382,
    scent: 'Fresh Mint',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-fruit',
    art: 'ED0909',
    ean: '7640125380385',
    image: 'ed0909.webp',
    w: 228,
    h: 382,
    scent: 'Fruit',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-vanilla',
    art: 'ED0101',
    ean: '7640125380309',
    image: 'ed0101.webp',
    w: 228,
    h: 382,
    scent: 'Vanilla',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-new-car',
    art: 'ED0202',
    ean: '7640125380316',
    image: 'ed0202.webp',
    w: 228,
    h: 382,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-cherry',
    art: 'ED0404',
    ean: '7640186840477',
    image: 'ed0404.webp',
    w: 228,
    h: 382,
    scent: 'Cherry',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-passion',
    art: 'ED0303',
    ean: '7640186841764',
    image: 'ed0303.webp',
    w: 228,
    h: 382,
    scent: 'Passion',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-ocean-splash',
    art: 'ED0707',
    ean: '7640186841788',
    image: 'ed0707.webp',
    w: 228,
    h: 382,
    scent: 'Ocean Splash',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-tonic',
    art: 'ED1010',
    ean: '7640186841795',
    image: 'ed1010.webp',
    w: 228,
    h: 382,
    scent: 'Tonic',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-odour-neutraliser',
    art: 'ED1515',
    ean: '7640186841610',
    image: 'ed1515.webp',
    w: 228,
    h: 382,
    scent: 'Odour Neutraliser',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-flower',
    art: 'ED1313',
    ean: '7640125380323',
    image: 'ed1313.webp',
    w: 228,
    h: 382,
    scent: 'Flower',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'little-dog',
    slug: 'little-dog-pina-colada',
    art: 'ED1414',
    ean: '7640186841740',
    image: 'ed1414.webp',
    w: 228,
    h: 382,
    scent: 'Piña Colada',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-pup',
    slug: 'little-pup-minty-fresh',
    art: 'EP2754',
    ean: '7640186843614',
    image: 'ep2754.webp',
    w: 208,
    h: 336,
    scent: 'Minty Fresh',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-pup',
    slug: 'little-pup-mauve-magic',
    art: 'EP2455',
    ean: '7640186843621',
    image: 'ep2455.webp',
    w: 208,
    h: 336,
    scent: 'Mauve Magic',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-pup',
    slug: 'little-pup-new-car',
    art: 'EP0202',
    ean: '7640186843607',
    image: 'ep0202.webp',
    w: 208,
    h: 336,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-pup',
    slug: 'little-pup-blueberry-paws',
    art: 'EP3539',
    ean: '7640186843638',
    image: 'ep3539.webp',
    w: 208,
    h: 336,
    scent: 'Blueberry Paws',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-pup',
    slug: 'little-pup-vanilla-pup-sation',
    art: 'EP0101',
    ean: '7640186843584',
    image: 'ep0101.webp',
    w: 200,
    h: 336,
    scent: 'Vanilla Pup-sation',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'little-pup',
    slug: 'little-pup-sweet-snuggles',
    art: 'EP0309',
    ean: '7640186843591',
    image: 'ep0309.webp',
    w: 205,
    h: 336,
    scent: 'Sweet Snuggles',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-cat',
    slug: 'little-cat-new-car',
    art: 'LC0202',
    ean: '7640186846127',
    image: 'lc0202.webp',
    w: 222,
    h: 368,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-cat',
    slug: 'little-cat-pina-colada',
    art: 'LC1414',
    ean: '7640186846141',
    image: 'lc1414.webp',
    w: 222,
    h: 368,
    scent: 'Piña Colada',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-cat',
    slug: 'little-cat-wild-strawberry',
    art: 'LC1172',
    ean: '7640186846134',
    image: 'lc1172.webp',
    w: 222,
    h: 368,
    scent: 'Wild Strawberry',
    label: null,
    family: 'fruity',
    dims: null,
    price: null,
  },
  {
    line: 'little-cat',
    slug: 'little-cat-sport',
    art: 'LC4170',
    ean: '7640186846110',
    image: 'lc4170.webp',
    w: 222,
    h: 368,
    scent: 'Sport',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-duck',
    slug: 'little-duck-new-car',
    art: 'LD0202',
    ean: '7640186846097',
    image: 'ld0202.webp',
    w: 235,
    h: 380,
    scent: 'New Car',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-duck',
    slug: 'little-duck-happy-splash',
    art: 'LD0117',
    ean: '7640186845243',
    image: 'ld0117.webp',
    w: 235,
    h: 380,
    scent: 'Happy Splash',
    label: null,
    family: 'fresh',
    dims: null,
    price: null,
  },
  {
    line: 'little-duck',
    slug: 'little-duck-cashmere',
    art: 'LD1616',
    ean: '7640186846073',
    image: 'ld1616.webp',
    w: 235,
    h: 380,
    scent: 'Cashmere',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'little-duck',
    slug: 'little-duck-matcha',
    art: 'LD4374',
    ean: '7640186846103',
    image: 'ld4374.webp',
    w: 235,
    h: 380,
    scent: 'Matcha',
    label: null,
    family: null,
    dims: null,
    price: null,
  },
  {
    line: 'tumble-fresh',
    slug: 'tumble-fresh-lavender',
    art: 'TF2136',
    ean: '7640186840095',
    image: 'tf2136.webp',
    w: 216,
    h: 384,
    scent: 'Lavender',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'tumble-fresh',
    slug: 'tumble-fresh-blooming-orchid',
    art: 'TF1138',
    ean: '7640186840118',
    image: 'tf1138.webp',
    w: 224,
    h: 384,
    scent: 'Blooming Orchid',
    label: null,
    family: 'floral',
    dims: null,
    price: null,
  },
  {
    line: 'tumble-fresh',
    slug: 'tumble-fresh-vanilla-blossom',
    art: 'TF0137',
    ean: '7640186840101',
    image: 'tf0137.webp',
    w: 224,
    h: 381,
    scent: 'Vanilla Blossom',
    label: null,
    family: 'sweet',
    dims: null,
    price: null,
  },
  {
    line: 'at-work',
    slug: 'at-work-mouse-pad',
    art: 'LJ1023-7',
    ean: '7640186842730',
    image: 'lj1023-7.webp',
    w: 544,
    h: 650,
    scent: null,
    label: {
      hy: 'Մկնիկի գորգ',
      ru: 'Коврик для мыши',
      it: 'Tappetino per mouse',
      en: 'Mouse Pad',
    },
    family: null,
    dims: '23 × 19 cm',
    price: 3500,
  },
  {
    line: 'at-work',
    slug: 'at-work-notepad-a5',
    art: 'LJ1023-12',
    ean: '7640186843522',
    image: 'lj1023-12.webp',
    w: 440,
    h: 616,
    scent: null,
    label: {
      hy: 'Նոթատետր A5',
      ru: 'Блокнот A5',
      it: 'Blocco note A5',
      en: 'Notepad A5',
    },
    family: null,
    dims: 'A5, 50',
    price: 1500,
  },
  {
    line: 'at-work',
    slug: 'at-work-pencils-5-pcs',
    art: 'LJ1023-1',
    ean: '7640186842679',
    image: 'lj1023-1.webp',
    w: 320,
    h: 896,
    scent: null,
    label: {
      hy: 'Մատիտներ, 5 հատ',
      ru: 'Карандаши, 5 шт.',
      it: 'Matite, 5 pz',
      en: 'Pencils, 5 pcs',
    },
    family: null,
    dims: '17.5 × 0.7 cm',
    price: 1500,
  },
  {
    line: 'at-work',
    slug: 'at-work-rulers-5-pcs',
    art: 'LJ1023-6',
    ean: '7640186842723',
    image: 'lj1023-6.webp',
    w: 207,
    h: 821,
    scent: null,
    label: {
      hy: 'Քանոններ, 5 հատ',
      ru: 'Линейки, 5 шт.',
      it: 'Righelli, 5 pz',
      en: 'Rulers, 5 pcs',
    },
    family: null,
    dims: '15 cm',
    price: 1500,
  },
  {
    line: 'at-work',
    slug: 'at-work-multicolour-pens-5-pcs',
    art: 'LJ1023-2',
    ean: '7640186842686',
    image: 'lj1023-2.webp',
    w: 440,
    h: 736,
    scent: null,
    label: {
      hy: 'Բազմագույն գրիչներ, 5 հատ',
      ru: 'Многоцветные ручки, 5 шт.',
      it: 'Penne multicolore, 5 pz',
      en: 'Multicolour Pens, 5 pcs',
    },
    family: null,
    dims: '14.6 × 1.5 cm',
    price: 2500,
  },
  {
    line: 'merchandise',
    slug: 'merchandise-t-shirt',
    art: 'LJ1023-17',
    ean: '7640186843577',
    image: 'lj1023-17.webp',
    w: 318,
    h: 373,
    scent: null,
    label: {
      hy: 'Շապիկ',
      ru: 'Футболка',
      it: 'T-shirt',
      en: 'T-Shirt',
    },
    family: null,
    dims: null,
    price: 6500,
  },
  {
    line: 'merchandise',
    slug: 'merchandise-bath-bombs',
    art: 'LJ1023-8',
    ean: '7640186842747',
    image: 'lj1023-8.webp',
    w: 532,
    h: 442,
    scent: null,
    label: {
      hy: 'Լոգանքի գնդիկներ',
      ru: 'Бомбочки для ванны',
      it: 'Bombe da bagno',
      en: 'Bath Bombs',
    },
    family: null,
    dims: '31.5 × 26 × 4 cm',
    price: 6900,
  },
];
