/**
 * Seed content for static informational pages.
 *
 * IMPORTANT: these are TEMPLATES. The seller's legal details, return period,
 * delivery times and data-retention periods are not known yet, so they are
 * left as bracketed placeholders ([...]) that must be replaced before launch.
 * Pages with legalReviewRequired = true must be reviewed by a lawyer.
 *
 * Body format: plain text. Paragraphs are separated by a blank line,
 * headings start with "## ", bullet list items start with "- ".
 */

export type PageSeed = {
  slug: "delivery" | "payment" | "returns" | "faq" | "privacy" | "terms" | "contact" | "about";
  legalReviewRequired: boolean;
  t: Record<"hy" | "ru" | "it" | "en", { title: string; body: string; seoDescription: string }>;
};

/** Joins lines with "\n". Use "" for a blank line between paragraphs. */
const b = (...lines: string[]): string => lines.join("\n");

export const pages: PageSeed[] = [
  // ---------------------------------------------------------------- delivery
  {
    slug: "delivery",
    legalReviewRequired: true,
    t: {
      hy: {
        title: "Առաքում",
        seoDescription:
          "Առաքման տարածքները, արժեքը և ժամկետները. Ճշգրիտ պայմանները ցուցադրվում են պատվերի ձևակերպման ժամանակ։",
        body: b(
          "Մենք առաքում ենք պատվերները Հայաստանի Հանրապետության տարածքում։ Առաքման հասանելի եղանակները, տարածքները և արժեքը սահմանում է խանութը, և դրանք կարող են ժամանակ առ ժամանակ փոփոխվել։",
          "",
          "## Ինչպես իմանալ առաքման արժեքը",
          "",
          "Առաքման ճշգրիտ արժեքը ցուցադրվում է պատվերի ձևակերպման ժամանակ՝ հասցեն և առաքման եղանակն ընտրելուց հետո, մինչև պատվերի հաստատումը։ Բոլոր գները նշված են ՀՀ դրամով (֏)։",
          "",
          "- Առաքման տարածքները և եղանակները ցուցադրվում են պատվերի ձևակերպման էջում։",
          "- Եթե գործում է անվճար առաքման շեմ, այն նույնպես նշվում է պատվերի ձևակերպման ժամանակ։",
          "",
          "## Առաքման ժամկետներ",
          "",
          "- Երևան՝ [Առաքման ժամկետը Երևանում — ենթակա է հաստատման]",
          "- ՀՀ մարզեր՝ [Առաքման ժամկետը մարզերում — ենթակա է հաստատման]",
          "- Պատվերների ընդունում և մշակում՝ [Աշխատանքային ժամեր]",
          "",
          "Ժամկետները կարող են երկարել տոնական օրերին, անբարենպաստ եղանակային պայմաններում կամ առաքման ծառայությունից կախված այլ պատճառներով։ Նման դեպքերում մենք կկապվենք Ձեզ հետ։",
          "",
          "## Պատվերի ստացում",
          "",
          "Պատվերը ձևակերպելուց հետո մենք կարող ենք զանգահարել Ձեզ՝ մանրամասները ճշտելու համար։ Խնդրում ենք նշել ճիշտ հեռախոսահամար և հասցե։ Ստանալիս խորհուրդ ենք տալիս ստուգել փաթեթի ամբողջականությունը առաքիչի ներկայությամբ։",
          "",
          "## Հարցեր",
          "",
          "Առաքման վերաբերյալ հարցերի համար կապվեք մեզ հետ՝ [Հեռախոսահամար], [Էլ. փոստ]։",
        ),
      },
      ru: {
        title: "Доставка",
        seoDescription:
          "Регионы, стоимость и сроки доставки. Точные условия показываются при оформлении заказа.",
        body: b(
          "Мы доставляем заказы по территории Республики Армения. Доступные способы, регионы и стоимость доставки устанавливает магазин, и они могут время от времени меняться.",
          "",
          "## Как узнать стоимость доставки",
          "",
          "Точная стоимость доставки отображается при оформлении заказа — после выбора адреса и способа доставки, до подтверждения заказа. Все цены указаны в армянских драмах (֏).",
          "",
          "- Регионы и способы доставки показаны на странице оформления заказа.",
          "- Если действует порог бесплатной доставки, он также указан при оформлении заказа.",
          "",
          "## Сроки доставки",
          "",
          "- Ереван: [Срок доставки по Еревану — уточняется]",
          "- Регионы Армении: [Срок доставки в регионы — уточняется]",
          "- Приём и обработка заказов: [Часы работы]",
          "",
          "Сроки могут увеличиваться в праздничные дни, при неблагоприятной погоде или по другим причинам, зависящим от службы доставки. В таких случаях мы свяжемся с вами.",
          "",
          "## Получение заказа",
          "",
          "После оформления заказа мы можем позвонить вам, чтобы уточнить детали. Пожалуйста, указывайте верный номер телефона и адрес. При получении рекомендуем проверить целостность упаковки в присутствии курьера.",
          "",
          "## Вопросы",
          "",
          "По вопросам доставки свяжитесь с нами: [Телефон], [Эл. почта].",
        ),
      },
      it: {
        title: "Spedizione",
        seoDescription:
          "Zone, costi e tempi di consegna. Le condizioni esatte vengono mostrate durante il checkout.",
        body: b(
          "Consegniamo gli ordini sul territorio della Repubblica di Armenia. Le modalità di consegna disponibili, le zone servite e i costi sono stabiliti dal negozio e possono variare nel tempo.",
          "",
          "## Come conoscere il costo di consegna",
          "",
          "Il costo esatto della consegna viene mostrato durante il checkout, dopo aver scelto l'indirizzo e la modalità di consegna e prima di confermare l'ordine. Tutti i prezzi sono espressi in dram armeni (֏).",
          "",
          "- Le zone e le modalità di consegna sono indicate nella pagina di checkout.",
          "- Se è prevista una soglia per la consegna gratuita, viene indicata al checkout.",
          "",
          "## Tempi di consegna",
          "",
          "- Erevan: [Tempi di consegna a Erevan — da confermare]",
          "- Regioni dell'Armenia: [Tempi di consegna nelle regioni — da confermare]",
          "- Ricezione ed elaborazione degli ordini: [Orari di apertura]",
          "",
          "I tempi possono allungarsi nei giorni festivi, in caso di maltempo o per altri motivi legati al servizio di consegna. In questi casi ti contatteremo.",
          "",
          "## Ricezione dell'ordine",
          "",
          "Dopo l'ordine potremmo chiamarti per confermare i dettagli: ti chiediamo di indicare un numero di telefono e un indirizzo corretti. Alla consegna ti consigliamo di verificare l'integrità del pacco in presenza del corriere.",
          "",
          "## Domande",
          "",
          "Per domande sulla consegna contattaci: [Telefono], [Email].",
        ),
      },
      en: {
        title: "Delivery",
        seoDescription:
          "Delivery regions, costs and timing. Exact terms are shown at checkout before you confirm your order.",
        body: b(
          "We deliver orders within the Republic of Armenia. The available delivery methods, regions and prices are set by the store and may change from time to time.",
          "",
          "## How to find out the delivery cost",
          "",
          "The exact delivery cost is shown at checkout, after you choose your address and delivery method and before you confirm the order. All prices are in Armenian dram (֏).",
          "",
          "- Delivery regions and methods are listed on the checkout page.",
          "- If a free-delivery threshold applies, it is also shown at checkout.",
          "",
          "## Delivery times",
          "",
          "- Yerevan: [Delivery time in Yerevan — to be confirmed]",
          "- Regions of Armenia: [Delivery time in the regions — to be confirmed]",
          "- Order processing hours: [Working hours]",
          "",
          "Delivery may take longer on public holidays, in bad weather or for other reasons related to the delivery service. If that happens, we will contact you.",
          "",
          "## Receiving your order",
          "",
          "After you place an order, we may call you to confirm the details, so please provide a correct phone number and address. When receiving the parcel, we recommend checking that the packaging is intact in the courier's presence.",
          "",
          "## Questions",
          "",
          "For delivery questions, contact us: [Phone], [Email].",
        ),
      },
    },
  },

  // ----------------------------------------------------------------- payment
  {
    slug: "payment",
    legalReviewRequired: true,
    t: {
      hy: {
        title: "Վճարում",
        seoDescription:
          "Վճարման եղանակներ՝ կանխիկ առաքիչին, իսկ Idram, Telcell և բանկային քարտ՝ ակտիվացումից հետո։ Քարտի տվյալները չենք պահում։",
        body: b(
          "Պատվերի ձևակերպման ժամանակ կարող եք ընտրել Ձեզ հարմար վճարման եղանակը։ Այս պահին հասանելի եղանակները միշտ ցուցադրվում են պատվերի ձևակերպման էջում։ Բոլոր գները նշված են ՀՀ դրամով (֏)։",
          "",
          "## Կանխիկ՝ առաքիչին",
          "",
          "Պատվերի համար վճարում եք կանխիկ՝ այն ստանալու պահին, առաքիչին։ Վճարման ենթակա գումարը, ներառյալ առաքման արժեքը, նշվում է պատվերի հաստատման մեջ։",
          "",
          "## Առցանց վճարում",
          "",
          "Հետևյալ եղանակները հասանելի կլինեն ակտիվացումից հետո.",
          "",
          "- Idram — հասանելի կլինի ակտիվացումից հետո",
          "- Telcell — հասանելի կլինի ակտիվացումից հետո",
          "- Բանկային քարտ — հասանելի կլինի ակտիվացումից հետո",
          "",
          "Առցանց վճարելիս Դուք կուղղորդվեք վճարային ծառայություն մատուցողի պաշտպանված էջ, որտեղ և կմուտքագրեք վճարման տվյալները։ Մեր խանութը չի ստանում և չի պահում Ձեր բանկային քարտի տվյալները։",
          "",
          "## Փաստաթղթեր",
          "",
          "Վճարումը հաստատող փաստաթուղթը տրամադրվում է Հայաստանի Հանրապետության օրենսդրությանը համապատասխան։ [Վճարման փաստաթղթի տրամադրման կարգը — ենթակա է հաստատման]",
          "",
          "## Հարցեր",
          "",
          "Վճարման վերաբերյալ հարցերի համար կապվեք մեզ հետ՝ [Հեռախոսահամար], [Էլ. փոստ]։",
        ),
      },
      ru: {
        title: "Оплата",
        seoDescription:
          "Способы оплаты: наличными курьеру, Idram, Telcell и банковская карта — после подключения. Данные карт мы не храним.",
        body: b(
          "При оформлении заказа вы можете выбрать удобный способ оплаты. Способы, доступные в данный момент, всегда отображаются на странице оформления заказа. Все цены указаны в армянских драмах (֏).",
          "",
          "## Наличными курьеру",
          "",
          "Вы оплачиваете заказ наличными курьеру в момент получения. Сумма к оплате, включая стоимость доставки, указывается в подтверждении заказа.",
          "",
          "## Онлайн-оплата",
          "",
          "Следующие способы станут доступны после подключения:",
          "",
          "- Idram — будет доступен после подключения",
          "- Telcell — будет доступен после подключения",
          "- Банковская карта — будет доступна после подключения",
          "",
          "При онлайн-оплате вы будете перенаправлены на защищённую страницу платёжного провайдера и введёте платёжные данные там. Наш магазин не получает и не хранит данные вашей банковской карты.",
          "",
          "## Документы",
          "",
          "Документ, подтверждающий оплату, предоставляется в соответствии с законодательством Республики Армения. [Порядок выдачи платёжного документа — уточняется]",
          "",
          "## Вопросы",
          "",
          "По вопросам оплаты свяжитесь с нами: [Телефон], [Эл. почта].",
        ),
      },
      it: {
        title: "Pagamento",
        seoDescription:
          "Metodi di pagamento: contanti al corriere; Idram, Telcell e carta bancaria disponibili dopo l'attivazione. Non conserviamo i dati delle carte.",
        body: b(
          "Al momento dell'ordine puoi scegliere il metodo di pagamento che preferisci. I metodi disponibili in quel momento sono sempre indicati nella pagina di checkout. Tutti i prezzi sono espressi in dram armeni (֏).",
          "",
          "## Contanti al corriere",
          "",
          "Paghi l'ordine in contanti al corriere al momento della consegna. L'importo da pagare, comprese le spese di consegna, è indicato nella conferma dell'ordine.",
          "",
          "## Pagamento online",
          "",
          "I seguenti metodi saranno disponibili dopo l'attivazione:",
          "",
          "- Idram — disponibile dopo l'attivazione",
          "- Telcell — disponibile dopo l'attivazione",
          "- Carta bancaria — disponibile dopo l'attivazione",
          "",
          "Con il pagamento online verrai reindirizzato alla pagina protetta del fornitore del servizio di pagamento, dove inserirai i dati di pagamento. Il nostro negozio non riceve e non conserva i dati della tua carta.",
          "",
          "## Documenti",
          "",
          "Il documento che attesta il pagamento viene rilasciato in conformità con la legislazione della Repubblica di Armenia. [Modalità di rilascio del documento di pagamento — da confermare]",
          "",
          "## Domande",
          "",
          "Per domande sui pagamenti contattaci: [Telefono], [Email].",
        ),
      },
      en: {
        title: "Payment",
        seoDescription:
          "Payment options: cash to the courier; Idram, Telcell and bank card available once activated. We never store your card details.",
        body: b(
          "You can choose a convenient payment method at checkout. The methods currently available are always shown on the checkout page. All prices are in Armenian dram (֏).",
          "",
          "## Cash to the courier",
          "",
          "You pay for your order in cash to the courier when you receive it. The amount due, including delivery, is shown in your order confirmation.",
          "",
          "## Online payment",
          "",
          "The following methods will be available once activated:",
          "",
          "- Idram — available once activated",
          "- Telcell — available once activated",
          "- Bank card — available once activated",
          "",
          "When paying online, you are redirected to the payment provider's secure page and enter your payment details there. Our store never receives or stores your card details.",
          "",
          "## Documents",
          "",
          "A document confirming payment is issued in accordance with the legislation of the Republic of Armenia. [How the payment document is issued — to be confirmed]",
          "",
          "## Questions",
          "",
          "For payment questions, contact us: [Phone], [Email].",
        ),
      },
    },
  },

  // ----------------------------------------------------------------- returns
  {
    slug: "returns",
    legalReviewRequired: true,
    t: {
      hy: {
        title: "Վերադարձ և փոխանակում",
        seoDescription:
          "Ինչպես վերադարձնել կամ փոխանակել ապրանքը՝ ՀՀ օրենսդրությանը համապատասխան։ Պայմանները և ժամկետները՝ այս էջում։",
        body: b(
          "Ապրանքի վերադարձը և փոխանակումն իրականացվում են Հայաստանի Հանրապետության սպառողների իրավունքների պաշտպանության մասին օրենսդրությանը համապատասխան։",
          "",
          "## Վերադարձի ժամկետ",
          "",
          "Վերադարձի կամ փոխանակման դիմում կարող եք ներկայացնել ապրանքը ստանալուց հետո [Վերադարձի ժամկետը օրերով — ենթակա է հաստատման] ընթացքում։",
          "",
          "## Վերադարձի պայմաններ",
          "",
          "[Ապրանքի վերադարձի պայմանները — ենթակա է հաստատման]",
          "",
          "Եթե ապրանքն ունի թերություն, վնասված է առաքման ժամանակ կամ չի համապատասխանում պատվերին, խնդրում ենք հնարավորինս շուտ կապվել մեզ հետ։ Նման դեպքերը քննարկվում են օրենսդրությանը համապատասխան։",
          "",
          "## Ինչպես ներկայացնել դիմում",
          "",
          "- Կապվեք մեզ հետ հեռախոսով կամ էլ. փոստով՝ նշելով պատվերի համարը։",
          "- Համառոտ նկարագրեք վերադարձի պատճառը և, անհրաժեշտության դեպքում, կցեք լուսանկար։",
          "- Մենք կհաստատենք դիմումը և կտեղեկացնենք ապրանքը վերադարձնելու կարգի մասին։",
          "",
          "## Գումարի վերադարձ",
          "",
          "Գումարը վերադարձվում է օրենսդրությամբ սահմանված կարգով։ Վերադարձի եղանակը և ժամկետը՝ [Գումարի վերադարձի եղանակը և ժամկետը — ենթակա է հաստատման]։",
          "",
          "## Կոնտակտներ",
          "",
          "[Հեռախոսահամար], [Էլ. փոստ]",
        ),
      },
      ru: {
        title: "Возврат и обмен",
        seoDescription:
          "Как вернуть или обменять товар в соответствии с законодательством РА. Условия и сроки — на этой странице.",
        body: b(
          "Возврат и обмен товара осуществляются в соответствии с законодательством Республики Армения о защите прав потребителей.",
          "",
          "## Срок возврата",
          "",
          "Заявку на возврат или обмен можно подать в течение [Срок возврата в днях — уточняется] после получения товара.",
          "",
          "## Условия возврата",
          "",
          "[Условия возврата товара — уточняются]",
          "",
          "Если товар имеет дефект, был повреждён при доставке или не соответствует заказу, пожалуйста, свяжитесь с нами как можно скорее. Такие случаи рассматриваются в соответствии с законодательством.",
          "",
          "## Как подать заявку",
          "",
          "- Свяжитесь с нами по телефону или электронной почте и укажите номер заказа.",
          "- Кратко опишите причину возврата и при необходимости приложите фотографию.",
          "- Мы подтвердим заявку и сообщим, как вернуть товар.",
          "",
          "## Возврат денег",
          "",
          "Деньги возвращаются в порядке, установленном законодательством. Способ и срок возврата: [Способ и срок возврата денег — уточняются].",
          "",
          "## Контакты",
          "",
          "[Телефон], [Эл. почта]",
        ),
      },
      it: {
        title: "Resi e cambi",
        seoDescription:
          "Come restituire o cambiare un prodotto secondo la legislazione armena. Condizioni e termini in questa pagina.",
        body: b(
          "Resi e cambi sono gestiti in conformità con la legislazione della Repubblica di Armenia in materia di tutela dei consumatori.",
          "",
          "## Termine per il reso",
          "",
          "Puoi richiedere un reso o un cambio entro [Termine di reso in giorni — da confermare] dal ricevimento del prodotto.",
          "",
          "## Condizioni di reso",
          "",
          "[Condizioni per il reso dei prodotti — da confermare]",
          "",
          "Se il prodotto è difettoso, è stato danneggiato durante la consegna o non corrisponde all'ordine, contattaci il prima possibile. Questi casi vengono gestiti in conformità con la legislazione.",
          "",
          "## Come fare richiesta",
          "",
          "- Contattaci per telefono o email indicando il numero dell'ordine.",
          "- Descrivi brevemente il motivo del reso e, se utile, allega una foto.",
          "- Confermeremo la richiesta e ti spiegheremo come restituire il prodotto.",
          "",
          "## Rimborso",
          "",
          "Il rimborso avviene secondo le modalità previste dalla legislazione. Modalità e tempi: [Modalità e tempi di rimborso — da confermare].",
          "",
          "## Contatti",
          "",
          "[Telefono], [Email]",
        ),
      },
      en: {
        title: "Returns and exchanges",
        seoDescription:
          "How to return or exchange a product in accordance with Armenian law. Conditions and timeframes on this page.",
        body: b(
          "Returns and exchanges are handled in accordance with the consumer protection legislation of the Republic of Armenia.",
          "",
          "## Return period",
          "",
          "You can request a return or exchange within [Return period in days — to be confirmed] of receiving your order.",
          "",
          "## Return conditions",
          "",
          "[Conditions for returning products — to be confirmed]",
          "",
          "If a product is defective, was damaged in delivery or does not match your order, please contact us as soon as possible. Such cases are handled in accordance with the law.",
          "",
          "## How to request a return",
          "",
          "- Contact us by phone or email and include your order number.",
          "- Briefly describe the reason for the return and attach a photo if helpful.",
          "- We will confirm your request and explain how to send the product back.",
          "",
          "## Refunds",
          "",
          "Refunds are made in the manner established by law. Method and timing: [Refund method and timing — to be confirmed].",
          "",
          "## Contact",
          "",
          "[Phone], [Email]",
        ),
      },
    },
  },

  // --------------------------------------------------------------------- faq
  {
    slug: "faq",
    legalReviewRequired: false,
    t: {
      hy: {
        title: "Հաճախ տրվող հարցեր",
        seoDescription:
          "Պատասխաններ հաճախ տրվող հարցերին՝ բույրի ընտրություն, տեղադրում, առաքում, վճարում, վերադարձ և կապ։",
        body: b(
          "## Ինչպե՞ս ընտրել բույրը",
          "",
          "Օգտվեք մեր կայքի բույրի ընտրության գործիքից. պատասխանեք մի քանի հարցի, և այն կառաջարկի Ձեր նախընտրություններին համապատասխան բույրեր։ Կարող եք նաև կարդալ յուրաքանչյուր ապրանքի էջում ներկայացված բույրի նկարագրությունը։",
          "",
          "## Ինչպե՞ս տեղադրել օդափոխիչի վանդակաճաղին ամրացվող բուրավետիչը",
          "",
          "Հետևեք փաթեթավորման վրա նշված հրահանգներին։ Տեղադրելիս համոզվեք, որ բուրավետիչը ամուր է նստած և չի խանգարում վարելուն։",
          "",
          "## Որքա՞ն է տևում առաքումը",
          "",
          "Առաքման ժամկետները և արժեքը կախված են տարածքից և ընտրված եղանակից։ Դրանք ցուցադրվում են պատվերի ձևակերպման ժամանակ, իսկ մանրամասները՝ «Առաքում» էջում։",
          "",
          "## Ինչպե՞ս կարող եմ վճարել",
          "",
          "Կարող եք վճարել կանխիկ՝ առաքիչին։ Idram, Telcell և բանկային քարտով վճարումը հասանելի կլինի ակտիվացումից հետո։ Մանրամասները՝ «Վճարում» էջում։",
          "",
          "## Կարո՞ղ եմ վերադարձնել ապրանքը",
          "",
          "Այո, Հայաստանի Հանրապետության օրենսդրությանը համապատասխան։ Պայմանները և ժամկետները ներկայացված են «Վերադարձ և փոխանակում» էջում։",
          "",
          "## Կարո՞ղ եմ փոփոխել կամ չեղարկել պատվերը",
          "",
          "Կապվեք մեզ հետ որքան հնարավոր է շուտ՝ նշելով պատվերի համարը։ Եթե պատվերը դեռ չի ուղարկվել, կփորձենք օգնել։",
          "",
          "## Ինչպե՞ս կապվել Ձեզ հետ",
          "",
          "- Հեռախոս՝ [Հեռախոսահամար]",
          "- Էլ. փոստ՝ [Էլ. փոստ]",
          "- Աշխատանքային ժամեր՝ [Աշխատանքային ժամեր]",
        ),
      },
      ru: {
        title: "Частые вопросы",
        seoDescription:
          "Ответы на частые вопросы: выбор аромата, установка, доставка, оплата, возврат и контакты.",
        body: b(
          "## Как выбрать аромат?",
          "",
          "Воспользуйтесь подбором аромата на нашем сайте: ответьте на несколько вопросов, и он предложит ароматы под ваши предпочтения. Также можно прочитать описание аромата на странице каждого товара.",
          "",
          "## Как установить ароматизатор на дефлектор?",
          "",
          "Следуйте инструкции на упаковке. При установке убедитесь, что ароматизатор держится надёжно и не мешает управлению автомобилем.",
          "",
          "## Сколько идёт доставка?",
          "",
          "Сроки и стоимость доставки зависят от региона и выбранного способа. Они отображаются при оформлении заказа, подробности — на странице «Доставка».",
          "",
          "## Как можно оплатить заказ?",
          "",
          "Можно оплатить наличными курьеру. Оплата через Idram, Telcell и банковской картой станет доступна после подключения. Подробности — на странице «Оплата».",
          "",
          "## Можно ли вернуть товар?",
          "",
          "Да, в соответствии с законодательством Республики Армения. Условия и сроки описаны на странице «Возврат и обмен».",
          "",
          "## Можно ли изменить или отменить заказ?",
          "",
          "Свяжитесь с нами как можно скорее и укажите номер заказа. Если заказ ещё не отправлен, мы постараемся помочь.",
          "",
          "## Как с вами связаться?",
          "",
          "- Телефон: [Телефон]",
          "- Эл. почта: [Эл. почта]",
          "- Часы работы: [Часы работы]",
        ),
      },
      it: {
        title: "Domande frequenti",
        seoDescription:
          "Risposte alle domande frequenti: scelta della fragranza, installazione, consegna, pagamento, resi e contatti.",
        body: b(
          "## Come scelgo la fragranza?",
          "",
          "Usa il nostro strumento per la scelta della fragranza: rispondi a poche domande e ti suggerirà le fragranze più adatte ai tuoi gusti. Puoi anche leggere la descrizione della fragranza nella pagina di ogni prodotto.",
          "",
          "## Come installo il profumatore per bocchette?",
          "",
          "Segui le istruzioni riportate sulla confezione. Durante l'installazione assicurati che il profumatore sia ben fissato e non intralci la guida.",
          "",
          "## Quanto tempo richiede la consegna?",
          "",
          "Tempi e costi di consegna dipendono dalla zona e dalla modalità scelta. Vengono mostrati al checkout; trovi i dettagli nella pagina «Spedizione».",
          "",
          "## Come posso pagare?",
          "",
          "Puoi pagare in contanti al corriere. Il pagamento con Idram, Telcell e carta bancaria sarà disponibile dopo l'attivazione. Dettagli nella pagina «Pagamento».",
          "",
          "## Posso restituire un prodotto?",
          "",
          "Sì, in conformità con la legislazione della Repubblica di Armenia. Condizioni e termini sono descritti nella pagina «Resi e cambi».",
          "",
          "## Posso modificare o annullare un ordine?",
          "",
          "Contattaci il prima possibile indicando il numero dell'ordine. Se l'ordine non è ancora stato spedito, faremo il possibile per aiutarti.",
          "",
          "## Come posso contattarvi?",
          "",
          "- Telefono: [Telefono]",
          "- Email: [Email]",
          "- Orari: [Orari di apertura]",
        ),
      },
      en: {
        title: "Frequently asked questions",
        seoDescription:
          "Answers to common questions: choosing a scent, installation, delivery, payment, returns and how to reach us.",
        body: b(
          "## How do I choose a scent?",
          "",
          "Try the scent finder on our website: answer a few questions and it will suggest scents that match your preferences. You can also read the scent description on each product page.",
          "",
          "## How do I install a vent clip air freshener?",
          "",
          "Follow the instructions on the packaging. When installing, make sure the air freshener is held securely and does not interfere with driving.",
          "",
          "## How long does delivery take?",
          "",
          "Delivery times and costs depend on the region and the method you choose. They are shown at checkout, and you can find details on the Delivery page.",
          "",
          "## How can I pay?",
          "",
          "You can pay in cash to the courier. Payment via Idram, Telcell and bank card will be available once activated. See the Payment page for details.",
          "",
          "## Can I return a product?",
          "",
          "Yes, in accordance with the legislation of the Republic of Armenia. Conditions and timeframes are described on the Returns and exchanges page.",
          "",
          "## Can I change or cancel my order?",
          "",
          "Contact us as soon as possible and include your order number. If the order has not been dispatched yet, we will do our best to help.",
          "",
          "## How can I contact you?",
          "",
          "- Phone: [Phone]",
          "- Email: [Email]",
          "- Hours: [Working hours]",
        ),
      },
    },
  },

  // ----------------------------------------------------------------- privacy
  {
    slug: "privacy",
    legalReviewRequired: true,
    t: {
      hy: {
        title: "Գաղտնիության քաղաքականություն",
        seoDescription:
          "Ինչ անձնական տվյալներ ենք հավաքում պատվերի ձևակերպման ժամանակ, ինչ նպատակով և ինչպես կարող եք կառավարել դրանք։",
        body: b(
          "Սույն քաղաքականությունը նկարագրում է, թե ինչպես ենք մշակում Ձեր անձնական տվյալները այս կայքից օգտվելիս և պատվեր ձևակերպելիս։ Անձնական տվյալները մշակվում են Հայաստանի Հանրապետության անձնական տվյալների պաշտպանության մասին օրենսդրությանը համապատասխան։",
          "",
          "Թարմացման ամսաթիվ՝ [Թարմացման ամսաթիվ]",
          "",
          "## Տվյալների մշակողը",
          "",
          "[Վաճառողի իրավաբանական անվանումը], ՀՎՀՀ՝ [ՀՎՀՀ], հասցե՝ [Գրանցման հասցե]։",
          "",
          "## Ինչ տվյալներ ենք հավաքում",
          "",
          "Պատվեր ձևակերպելիս մենք հավաքում ենք՝",
          "",
          "- անուն,",
          "- հեռախոսահամար,",
          "- էլ. փոստի հասցե (ըստ ցանկության),",
          "- առաքման հասցե,",
          "- պատվերների պատմություն (պատվիրված ապրանքներ, գումարներ, ամսաթվեր, կարգավիճակներ)։",
          "",
          "Մենք չենք ստանում և չենք պահում բանկային քարտի տվյալներ. առցանց վճարումը, երբ այն հասանելի լինի, կիրականացվի վճարային ծառայություն մատուցողի պաշտպանված էջում։",
          "",
          "## Ինչ նպատակով",
          "",
          "- Պատվերի մշակում, հաստատում և առաքում։",
          "- Պատվերի վերաբերյալ Ձեզ հետ կապ հաստատում։",
          "- Վերադարձների և դիմումների քննարկում։",
          "- Օրենսդրությամբ սահմանված պարտավորությունների կատարում։",
          "",
          "## Cookie ֆայլեր և վերլուծություն",
          "",
          "Կայքի աշխատանքի համար անհրաժեշտ cookie ֆայլերն օգտագործվում են միշտ (օրինակ՝ զամբյուղը և լեզվի ընտրությունը պահելու համար)։ Վերլուծական cookie ֆայլերն օգտագործվում են միայն Ձեր համաձայնությամբ, և Դուք կարող եք ցանկացած պահի հետ կանչել այն։",
          "",
          "## Տվյալների փոխանցում",
          "",
          "Ձեր տվյալները կարող են փոխանցվել միայն այն անձանց, ովքեր անհրաժեշտ են պատվերը կատարելու համար (օրինակ՝ առաքման ծառայությանը), և միայն այդ նպատակով անհրաժեշտ ծավալով, ինչպես նաև օրենքով նախատեսված դեպքերում։",
          "",
          "## Պահպանման ժամկետ",
          "",
          "[Տվյալների պահպանման ժամկետը — ենթակա է հաստատման]",
          "",
          "## Ձեր իրավունքները",
          "",
          "Օրենսդրությանը համապատասխան՝ Դուք կարող եք պահանջել տեղեկություններ Ձեր տվյալների մասին, դրանց ուղղում կամ ոչնչացում, ինչպես նաև հետ կանչել տրված համաձայնությունը։ Դիմումների համար գրեք՝ [Էլ. փոստ] կամ զանգահարեք՝ [Հեռախոսահամար]։",
          "",
          "## Փոփոխություններ",
          "",
          "Մենք կարող ենք թարմացնել սույն քաղաքականությունը։ Գործող տարբերակը միշտ հրապարակված է այս էջում։",
        ),
      },
      ru: {
        title: "Политика конфиденциальности",
        seoDescription:
          "Какие персональные данные мы собираем при оформлении заказа, с какой целью и как вы можете ими управлять.",
        body: b(
          "Настоящая политика описывает, как мы обрабатываем ваши персональные данные при использовании сайта и оформлении заказа. Персональные данные обрабатываются в соответствии с законодательством Республики Армения о защите персональных данных.",
          "",
          "Дата обновления: [Дата обновления]",
          "",
          "## Оператор данных",
          "",
          "[Юридическое наименование продавца], ИНН: [ИНН / ՀՎՀՀ], адрес: [Юридический адрес].",
          "",
          "## Какие данные мы собираем",
          "",
          "При оформлении заказа мы собираем:",
          "",
          "- имя;",
          "- номер телефона;",
          "- адрес электронной почты (по желанию);",
          "- адрес доставки;",
          "- историю заказов (заказанные товары, суммы, даты, статусы).",
          "",
          "Мы не получаем и не храним данные банковских карт: онлайн-оплата, когда она станет доступна, будет проходить на защищённой странице платёжного провайдера.",
          "",
          "## Для чего",
          "",
          "- Обработка, подтверждение и доставка заказа.",
          "- Связь с вами по вопросам заказа.",
          "- Рассмотрение возвратов и обращений.",
          "- Выполнение обязанностей, установленных законодательством.",
          "",
          "## Cookie и аналитика",
          "",
          "Технически необходимые cookie используются всегда (например, чтобы сохранить корзину и выбранный язык). Аналитические cookie используются только с вашего согласия, и вы можете отозвать его в любой момент.",
          "",
          "## Передача данных",
          "",
          "Ваши данные могут передаваться только тем, кто необходим для исполнения заказа (например, службе доставки), и только в объёме, нужном для этой цели, а также в случаях, предусмотренных законом.",
          "",
          "## Срок хранения",
          "",
          "[Срок хранения данных — уточняется]",
          "",
          "## Ваши права",
          "",
          "В соответствии с законодательством вы можете запросить сведения о своих данных, их исправление или удаление, а также отозвать данное согласие. Для обращений пишите: [Эл. почта] или звоните: [Телефон].",
          "",
          "## Изменения",
          "",
          "Мы можем обновлять эту политику. Действующая редакция всегда опубликована на этой странице.",
        ),
      },
      it: {
        title: "Informativa sulla privacy",
        seoDescription:
          "Quali dati personali raccogliamo al checkout, per quale scopo e come puoi gestirli.",
        body: b(
          "La presente informativa descrive come trattiamo i tuoi dati personali quando utilizzi il sito ed effettui un ordine. I dati personali sono trattati in conformità con la legislazione della Repubblica di Armenia sulla protezione dei dati personali.",
          "",
          "Ultimo aggiornamento: [Data di aggiornamento]",
          "",
          "## Titolare del trattamento",
          "",
          "[Ragione sociale del venditore], codice fiscale: [Codice fiscale / ՀՎՀՀ], indirizzo: [Sede legale].",
          "",
          "## Quali dati raccogliamo",
          "",
          "Quando effettui un ordine raccogliamo:",
          "",
          "- nome;",
          "- numero di telefono;",
          "- indirizzo email (facoltativo);",
          "- indirizzo di consegna;",
          "- storico degli ordini (prodotti ordinati, importi, date, stati).",
          "",
          "Non riceviamo né conserviamo i dati delle carte bancarie: il pagamento online, quando sarà disponibile, avverrà sulla pagina protetta del fornitore del servizio di pagamento.",
          "",
          "## Per quali finalità",
          "",
          "- Elaborazione, conferma e consegna dell'ordine.",
          "- Comunicazioni con te relative all'ordine.",
          "- Gestione di resi e richieste.",
          "- Adempimento degli obblighi previsti dalla legge.",
          "",
          "## Cookie e analisi",
          "",
          "I cookie tecnici necessari sono sempre attivi (ad esempio per ricordare il carrello e la lingua scelta). I cookie analitici vengono utilizzati solo con il tuo consenso, che puoi revocare in qualsiasi momento.",
          "",
          "## Comunicazione dei dati",
          "",
          "I tuoi dati possono essere comunicati solo ai soggetti necessari per evadere l'ordine (ad esempio il servizio di consegna), nella misura strettamente necessaria, e nei casi previsti dalla legge.",
          "",
          "## Periodo di conservazione",
          "",
          "[Periodo di conservazione dei dati — da confermare]",
          "",
          "## I tuoi diritti",
          "",
          "In conformità con la legislazione puoi chiedere informazioni sui tuoi dati, la loro rettifica o cancellazione, e revocare il consenso prestato. Per le richieste scrivi a [Email] o chiama il [Telefono].",
          "",
          "## Modifiche",
          "",
          "Potremmo aggiornare questa informativa. La versione in vigore è sempre pubblicata in questa pagina.",
        ),
      },
      en: {
        title: "Privacy policy",
        seoDescription:
          "What personal data we collect at checkout, why we collect it and how you can manage it.",
        body: b(
          "This policy explains how we process your personal data when you use this website and place an order. Personal data is processed in accordance with the personal data protection legislation of the Republic of Armenia.",
          "",
          "Last updated: [Date of last update]",
          "",
          "## Data controller",
          "",
          "[Legal name of the seller], TIN: [TIN / ՀՎՀՀ], address: [Registered address].",
          "",
          "## What data we collect",
          "",
          "When you place an order, we collect:",
          "",
          "- your name;",
          "- your phone number;",
          "- your email address (optional);",
          "- your delivery address;",
          "- your order history (products ordered, amounts, dates, statuses).",
          "",
          "We do not receive or store bank card details: online payment, once available, will take place on the payment provider's secure page.",
          "",
          "## Why we use it",
          "",
          "- To process, confirm and deliver your order.",
          "- To contact you about your order.",
          "- To handle returns and requests.",
          "- To meet our obligations under the law.",
          "",
          "## Cookies and analytics",
          "",
          "Strictly necessary cookies are always used (for example, to remember your cart and chosen language). Analytics cookies are used only with your consent, which you can withdraw at any time.",
          "",
          "## Sharing your data",
          "",
          "Your data may be shared only with parties needed to fulfil your order (for example, the delivery service), only to the extent required for that purpose, and in cases provided for by law.",
          "",
          "## Retention",
          "",
          "[Data retention period — to be confirmed]",
          "",
          "## Your rights",
          "",
          "In accordance with the law, you may request information about your data, ask for it to be corrected or deleted, and withdraw consent you have given. For requests, email [Email] or call [Phone].",
          "",
          "## Changes",
          "",
          "We may update this policy. The current version is always published on this page.",
        ),
      },
    },
  },

  // ------------------------------------------------------------------- terms
  {
    slug: "terms",
    legalReviewRequired: true,
    t: {
      hy: {
        title: "Օգտագործման պայմաններ",
        seoDescription:
          "Կայքի օգտագործման և պատվերների ձևակերպման պայմանները՝ գներ, վճարում, առաքում, վերադարձ և պատասխանատվություն։",
        body: b(
          "Սույն պայմանները կարգավորում են կայքի օգտագործումը և կայքի միջոցով ապրանքների ձեռքբերումը։ Պատվեր ձևակերպելով՝ Դուք համաձայնում եք այս պայմաններին։",
          "",
          "Թարմացման ամսաթիվ՝ [Թարմացման ամսաթիվ]",
          "",
          "## Վաճառող",
          "",
          "- Իրավաբանական անվանում՝ [Վաճառողի իրավաբանական անվանումը]",
          "- ՀՎՀՀ՝ [ՀՎՀՀ]",
          "- Հասցե՝ [Գրանցման հասցե]",
          "- Հեռախոս՝ [Հեռախոսահամար]",
          "- Էլ. փոստ՝ [Էլ. փոստ]",
          "",
          "Little Joe անվանումը և ապրանքանիշը պատկանում են դրանց իրավատիրոջը։ Կայքում դրանք օգտագործվում են միայն վաճառվող ապրանքները նկարագրելու նպատակով։",
          "",
          "## Պատվեր",
          "",
          "Պատվերը համարվում է ընդունված այն հաստատելուց հետո։ Եթե ապրանքը հասանելի չէ կամ պատվերը հնարավոր չէ կատարել, մենք կկապվենք Ձեզ հետ՝ այլընտրանք առաջարկելու կամ պատվերը չեղարկելու համար։",
          "",
          "## Գներ",
          "",
          "Գները նշված են ՀՀ դրամով (֏)։ Կիրառվում է պատվերի ձևակերպման պահին կայքում նշված գինը։ Առաքման արժեքը ցուցադրվում է առանձին՝ մինչև պատվերի հաստատումը։",
          "",
          "## Վճարում և առաքում",
          "",
          "Վճարման և առաքման պայմանները ներկայացված են «Վճարում» և «Առաքում» էջերում և պատվերի ձևակերպման ժամանակ։",
          "",
          "## Վերադարձ",
          "",
          "Վերադարձը և փոխանակումն իրականացվում են ՀՀ օրենսդրությանը համապատասխան՝ «Վերադարձ և փոխանակում» էջում նկարագրված կարգով։",
          "",
          "## Ապրանքների մասին տեղեկատվություն",
          "",
          "Մենք ձգտում ենք ճշգրիտ ներկայացնել ապրանքները։ Լուսանկարներում գույները և փաթեթավորումը կարող են որոշ չափով տարբերվել իրականից։ Օգտագործելուց առաջ ծանոթացեք փաթեթավորման վրա նշված տեղեկություններին և նախազգուշացումներին։",
          "",
          "## Պատասխանատվություն",
          "",
          "Կողմերի պատասխանատվությունը սահմանվում է Հայաստանի Հանրապետության օրենսդրությանը համապատասխան։",
          "",
          "## Անձնական տվյալներ",
          "",
          "Անձնական տվյալների մշակումը նկարագրված է «Գաղտնիության քաղաքականություն» էջում։",
          "",
          "## Կիրառելի իրավունք",
          "",
          "Սույն պայմանների նկատմամբ կիրառվում է Հայաստանի Հանրապետության օրենսդրությունը։ Վեճերը լուծվում են բանակցությունների միջոցով, իսկ համաձայնության չգալու դեպքում՝ օրենսդրությամբ սահմանված կարգով։",
          "",
          "## Փոփոխություններ",
          "",
          "Մենք կարող ենք թարմացնել սույն պայմանները։ Ձևակերպված պատվերի նկատմամբ կիրառվում են դրա ձևակերպման պահին գործող պայմանները։",
        ),
      },
      ru: {
        title: "Условия использования",
        seoDescription:
          "Условия использования сайта и оформления заказов: цены, оплата, доставка, возврат и ответственность.",
        body: b(
          "Настоящие условия регулируют использование сайта и покупку товаров через сайт. Оформляя заказ, вы соглашаетесь с этими условиями.",
          "",
          "Дата обновления: [Дата обновления]",
          "",
          "## Продавец",
          "",
          "- Юридическое наименование: [Юридическое наименование продавца]",
          "- ИНН: [ИНН / ՀՎՀՀ]",
          "- Адрес: [Юридический адрес]",
          "- Телефон: [Телефон]",
          "- Эл. почта: [Эл. почта]",
          "",
          "Название и товарный знак Little Joe принадлежат их правообладателю. На сайте они используются исключительно для описания продаваемых товаров.",
          "",
          "## Заказ",
          "",
          "Заказ считается принятым после его подтверждения. Если товара нет в наличии или заказ невозможно выполнить, мы свяжемся с вами, чтобы предложить альтернативу или отменить заказ.",
          "",
          "## Цены",
          "",
          "Цены указаны в армянских драмах (֏). Применяется цена, указанная на сайте в момент оформления заказа. Стоимость доставки показывается отдельно до подтверждения заказа.",
          "",
          "## Оплата и доставка",
          "",
          "Условия оплаты и доставки описаны на страницах «Оплата» и «Доставка», а также отображаются при оформлении заказа.",
          "",
          "## Возврат",
          "",
          "Возврат и обмен осуществляются в соответствии с законодательством РА в порядке, описанном на странице «Возврат и обмен».",
          "",
          "## Информация о товарах",
          "",
          "Мы стараемся точно представлять товары. Цвета и упаковка на фотографиях могут несколько отличаться от реальных. Перед использованием ознакомьтесь с информацией и предупреждениями на упаковке.",
          "",
          "## Ответственность",
          "",
          "Ответственность сторон определяется в соответствии с законодательством Республики Армения.",
          "",
          "## Персональные данные",
          "",
          "Обработка персональных данных описана на странице «Политика конфиденциальности».",
          "",
          "## Применимое право",
          "",
          "К настоящим условиям применяется законодательство Республики Армения. Споры решаются путём переговоров, а при недостижении согласия — в порядке, установленном законодательством.",
          "",
          "## Изменения",
          "",
          "Мы можем обновлять настоящие условия. К оформленному заказу применяются условия, действовавшие на момент его оформления.",
        ),
      },
      it: {
        title: "Termini e condizioni",
        seoDescription:
          "Condizioni d'uso del sito e di acquisto: prezzi, pagamento, consegna, resi e responsabilità.",
        body: b(
          "I presenti termini regolano l'utilizzo del sito e l'acquisto di prodotti tramite il sito. Effettuando un ordine accetti questi termini.",
          "",
          "Ultimo aggiornamento: [Data di aggiornamento]",
          "",
          "## Venditore",
          "",
          "- Ragione sociale: [Ragione sociale del venditore]",
          "- Codice fiscale: [Codice fiscale / ՀՎՀՀ]",
          "- Indirizzo: [Sede legale]",
          "- Telefono: [Telefono]",
          "- Email: [Email]",
          "",
          "Il nome e il marchio Little Joe appartengono al rispettivo titolare. Sul sito sono utilizzati esclusivamente per descrivere i prodotti in vendita.",
          "",
          "## Ordini",
          "",
          "L'ordine si considera accettato dopo la sua conferma. Se un prodotto non è disponibile o l'ordine non può essere evaso, ti contatteremo per proporti un'alternativa o annullare l'ordine.",
          "",
          "## Prezzi",
          "",
          "I prezzi sono espressi in dram armeni (֏). Si applica il prezzo indicato sul sito al momento dell'ordine. Il costo di consegna viene mostrato separatamente prima della conferma dell'ordine.",
          "",
          "## Pagamento e consegna",
          "",
          "Le condizioni di pagamento e consegna sono descritte nelle pagine «Pagamento» e «Spedizione» e vengono mostrate al checkout.",
          "",
          "## Resi",
          "",
          "Resi e cambi sono gestiti in conformità con la legislazione armena, secondo quanto descritto nella pagina «Resi e cambi».",
          "",
          "## Informazioni sui prodotti",
          "",
          "Ci impegniamo a presentare i prodotti in modo accurato. Colori e confezioni nelle fotografie possono differire leggermente dalla realtà. Prima dell'uso leggi le informazioni e le avvertenze riportate sulla confezione.",
          "",
          "## Responsabilità",
          "",
          "La responsabilità delle parti è determinata in conformità con la legislazione della Repubblica di Armenia.",
          "",
          "## Dati personali",
          "",
          "Il trattamento dei dati personali è descritto nella pagina «Informativa sulla privacy».",
          "",
          "## Legge applicabile",
          "",
          "Ai presenti termini si applica la legislazione della Repubblica di Armenia. Le controversie sono risolte in via amichevole e, in mancanza di accordo, secondo le modalità previste dalla legge.",
          "",
          "## Modifiche",
          "",
          "Potremmo aggiornare i presenti termini. A ciascun ordine si applicano i termini in vigore al momento in cui è stato effettuato.",
        ),
      },
      en: {
        title: "Terms and conditions",
        seoDescription:
          "Terms for using the website and placing orders: prices, payment, delivery, returns and liability.",
        body: b(
          "These terms govern the use of this website and the purchase of products through it. By placing an order, you agree to these terms.",
          "",
          "Last updated: [Date of last update]",
          "",
          "## Seller",
          "",
          "- Legal name: [Legal name of the seller]",
          "- TIN: [TIN / ՀՎՀՀ]",
          "- Address: [Registered address]",
          "- Phone: [Phone]",
          "- Email: [Email]",
          "",
          "The Little Joe name and trademark belong to their respective owner. On this website they are used solely to describe the products offered for sale.",
          "",
          "## Orders",
          "",
          "An order is considered accepted once it has been confirmed. If a product is unavailable or the order cannot be fulfilled, we will contact you to offer an alternative or cancel the order.",
          "",
          "## Prices",
          "",
          "Prices are in Armenian dram (֏). The price shown on the website at the time of ordering applies. The delivery cost is shown separately before you confirm the order.",
          "",
          "## Payment and delivery",
          "",
          "Payment and delivery terms are described on the Payment and Delivery pages and are shown at checkout.",
          "",
          "## Returns",
          "",
          "Returns and exchanges are handled in accordance with Armenian law, as described on the Returns and exchanges page.",
          "",
          "## Product information",
          "",
          "We aim to present our products accurately. Colours and packaging in photographs may differ slightly from the actual items. Before use, please read the information and warnings on the packaging.",
          "",
          "## Liability",
          "",
          "The liability of the parties is determined in accordance with the legislation of the Republic of Armenia.",
          "",
          "## Personal data",
          "",
          "How we process personal data is described in our Privacy policy.",
          "",
          "## Governing law",
          "",
          "These terms are governed by the legislation of the Republic of Armenia. Disputes are resolved through negotiation and, failing agreement, in the manner established by law.",
          "",
          "## Changes",
          "",
          "We may update these terms. Each order is governed by the terms in effect at the time it was placed.",
        ),
      },
    },
  },

  // ----------------------------------------------------------------- contact
  {
    slug: "contact",
    legalReviewRequired: false,
    t: {
      hy: {
        title: "Կապ",
        seoDescription:
          "Կապվեք մեզ հետ պատվերների, առաքման, վճարման և վերադարձի հարցերով։ Հեռախոս, էլ. փոստ, հասցե և աշխատանքային ժամեր։",
        body: b(
          "Հարցեր ունե՞ք պատվերի, բույրերի, առաքման կամ վերադարձի վերաբերյալ։ Սիրով կօգնենք։",
          "",
          "## Կոնտակտներ",
          "",
          "- Հեռախոս՝ [Հեռախոսահամար]",
          "- Էլ. փոստ՝ [Էլ. փոստ]",
          "- Հասցե՝ [Հասցե]",
          "- Աշխատանքային ժամեր՝ [Աշխատանքային ժամեր]",
          "",
          "## Սոցիալական ցանցեր",
          "",
          "- Instagram՝ [Instagram հղում]",
          "- Facebook՝ [Facebook հղում]",
          "",
          "## Վաճառող",
          "",
          "[Վաճառողի իրավաբանական անվանումը], ՀՎՀՀ՝ [ՀՎՀՀ], [Գրանցման հասցե]",
          "",
          "Պատվերի վերաբերյալ դիմելիս խնդրում ենք նշել պատվերի համարը, որպեսզի կարողանանք ավելի արագ օգնել։",
        ),
      },
      ru: {
        title: "Контакты",
        seoDescription:
          "Свяжитесь с нами по вопросам заказов, доставки, оплаты и возврата. Телефон, эл. почта, адрес и часы работы.",
        body: b(
          "Есть вопросы о заказе, ароматах, доставке или возврате? Мы с удовольствием поможем.",
          "",
          "## Контакты",
          "",
          "- Телефон: [Телефон]",
          "- Эл. почта: [Эл. почта]",
          "- Адрес: [Адрес]",
          "- Часы работы: [Часы работы]",
          "",
          "## Социальные сети",
          "",
          "- Instagram: [Ссылка на Instagram]",
          "- Facebook: [Ссылка на Facebook]",
          "",
          "## Продавец",
          "",
          "[Юридическое наименование продавца], ИНН: [ИНН / ՀՎՀՀ], [Юридический адрес]",
          "",
          "Обращаясь по поводу заказа, пожалуйста, укажите его номер — так мы сможем помочь быстрее.",
        ),
      },
      it: {
        title: "Contatti",
        seoDescription:
          "Contattaci per ordini, consegne, pagamenti e resi. Telefono, email, indirizzo e orari.",
        body: b(
          "Hai domande su un ordine, sulle fragranze, sulla consegna o sui resi? Saremo lieti di aiutarti.",
          "",
          "## Contatti",
          "",
          "- Telefono: [Telefono]",
          "- Email: [Email]",
          "- Indirizzo: [Indirizzo]",
          "- Orari: [Orari di apertura]",
          "",
          "## Social",
          "",
          "- Instagram: [Link Instagram]",
          "- Facebook: [Link Facebook]",
          "",
          "## Venditore",
          "",
          "[Ragione sociale del venditore], codice fiscale: [Codice fiscale / ՀՎՀՀ], [Sede legale]",
          "",
          "Se ci scrivi per un ordine, indica il numero dell'ordine: così potremo aiutarti più rapidamente.",
        ),
      },
      en: {
        title: "Contact",
        seoDescription:
          "Get in touch about orders, delivery, payment and returns. Phone, email, address and opening hours.",
        body: b(
          "Have a question about an order, our scents, delivery or returns? We are happy to help.",
          "",
          "## Contact details",
          "",
          "- Phone: [Phone]",
          "- Email: [Email]",
          "- Address: [Address]",
          "- Hours: [Working hours]",
          "",
          "## Social media",
          "",
          "- Instagram: [Instagram link]",
          "- Facebook: [Facebook link]",
          "",
          "## Seller",
          "",
          "[Legal name of the seller], TIN: [TIN / ՀՎՀՀ], [Registered address]",
          "",
          "If you are contacting us about an order, please include the order number so we can help you faster.",
        ),
      },
    },
  },

  // ------------------------------------------------------------------- about
  {
    slug: "about",
    legalReviewRequired: false,
    t: {
      hy: {
        title: "Մեր մասին",
        seoDescription:
          "Little Joe ավտոմեքենայի և տան բուրավետիչներ Հայաստանում՝ առաքմամբ և հարմար վճարմամբ։",
        body: b(
          "Little Joe-ն ավտոմեքենայի և տան բուրավետիչների ապրանքանիշ է։ Մեր խանութում կարող եք ընտրել Ձեզ դուր եկող բույրը և պատվիրել այն առաքմամբ Հայաստանում։",
          "",
          "## Ապրանքանիշի մասին",
          "",
          "Ապրանքանիշի մասին ստուգված տեղեկությունները, այդ թվում՝ ծագումը և արտադրողը, կհրապարակվեն արտադրողի պաշտոնական նյութերով հաստատվելուց հետո։",
          "",
          "[Ապրանքանիշի ստուգված պատմությունը՝ Drive Int. AG-ի պաշտոնական նյութերի հիման վրա — սպասվում է]",
          "",
          "## Խանութի մասին",
          "",
          "Մենք ձգտում ենք բույր ընտրելը դարձնել պարզ և հաճելի՝ յուրաքանչյուր բույրի հստակ նկարագրությամբ, բույրի ընտրության գործիքով և պատվերի հարմար ձևակերպմամբ։",
          "",
          "Վաճառող՝ [Վաճառողի իրավաբանական անվանումը], ՀՎՀՀ՝ [ՀՎՀՀ]։",
          "",
          "Հարցերի դեպքում այցելեք «Կապ» էջը։",
        ),
      },
      ru: {
        title: "О нас",
        seoDescription:
          "Ароматизаторы Little Joe для автомобиля и дома в Армении — с доставкой и удобной оплатой.",
        body: b(
          "Little Joe — бренд ароматизаторов для автомобиля и дома. В нашем магазине вы можете выбрать аромат по душе и заказать его с доставкой по Армении.",
          "",
          "## О бренде",
          "",
          "Проверенные сведения о бренде, в том числе о его происхождении и производителе, будут опубликованы после подтверждения по официальным материалам производителя.",
          "",
          "[Проверенная история бренда по официальным материалам Drive Int. AG — ожидается]",
          "",
          "## О магазине",
          "",
          "Мы хотим, чтобы выбор аромата был простым и приятным: с понятным описанием каждого аромата, подбором аромата и удобным оформлением заказа.",
          "",
          "Продавец: [Юридическое наименование продавца], ИНН: [ИНН / ՀՎՀՀ].",
          "",
          "Если у вас есть вопросы, загляните на страницу «Контакты».",
        ),
      },
      it: {
        title: "Chi siamo",
        seoDescription:
          "Profumatori Little Joe per auto e casa in Armenia, con consegna e pagamento comodo.",
        body: b(
          "Little Joe è un marchio di profumatori per auto e per la casa. Nel nostro negozio puoi scegliere la fragranza che preferisci e ordinarla con consegna in Armenia.",
          "",
          "## Il marchio",
          "",
          "Le informazioni verificate sul marchio, comprese origine e produttore, saranno pubblicate dopo la conferma sulla base dei materiali ufficiali del produttore.",
          "",
          "[Storia verificata del marchio dai materiali ufficiali di Drive Int. AG — in attesa]",
          "",
          "## Il negozio",
          "",
          "Vogliamo rendere la scelta della fragranza semplice e piacevole: con descrizioni chiare di ogni fragranza, uno strumento per scegliere la fragranza e un checkout comodo.",
          "",
          "Venditore: [Ragione sociale del venditore], codice fiscale: [Codice fiscale / ՀՎՀՀ].",
          "",
          "Per qualsiasi domanda visita la pagina «Contatti».",
        ),
      },
      en: {
        title: "About us",
        seoDescription:
          "Little Joe car and home fragrances in Armenia, with delivery and convenient payment.",
        body: b(
          "Little Joe is a brand of car and home fragrances. In our store you can choose a scent you love and order it with delivery in Armenia.",
          "",
          "## About the brand",
          "",
          "Verified facts about the brand, including its origin and manufacturer, will be published once confirmed against official manufacturer materials.",
          "",
          "[Verified brand story from official Drive Int. AG materials — pending]",
          "",
          "## About the store",
          "",
          "We want choosing a scent to feel simple and pleasant, with clear descriptions of every scent, a scent finder and an easy checkout.",
          "",
          "Seller: [Legal name of the seller], TIN: [TIN / ՀՎՀՀ].",
          "",
          "If you have any questions, please visit our Contact page.",
        ),
      },
    },
  },
];
