#!/usr/bin/env bash
#
# Brings the whole TuTak platform up on your own machine, with data in it.
#
#   ./scripts/demo-up.sh
#
# Everything runs in Docker — you do not need Node, pnpm, PostgreSQL or
# Redis installed. When it finishes it prints the URLs and the logins.
#
# Secrets are generated once into .env and then reused, so restarting does
# not invalidate the sessions you already have open. Nothing here is
# suitable for a real deployment: see docs/DEPLOYMENT.md for that.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bold()   { printf '\033[1m%s\033[0m\n' "$1"; }
green()  { printf '\033[0;32m%s\033[0m\n' "$1"; }
info()   { printf '\033[0;36m▸ %s\033[0m\n' "$1"; }
die()    { printf '\033[0;31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "Docker is not installed. Get it from https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "This needs Docker Compose v2 (bundled with modern Docker Desktop)."
docker info >/dev/null 2>&1 || die "The Docker daemon is not running. Start Docker Desktop and try again."

# ── 1. Secrets ──────────────────────────────────────────────────────────
# Generated, not committed. Regenerating them on every run would log every
# open browser tab out, so an existing .env is left alone.
random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

if [[ ! -f .env ]]; then
  info "Generating .env with fresh secrets"
  cat > .env <<EOF
# Generated by scripts/demo-up.sh — local demo stack only.
# Delete this file to rotate every secret; you will be logged out.
JWT_ACCESS_SECRET=$(random_secret)
JWT_REFRESH_SECRET=$(random_secret)

# The password every seeded demo account shares. Change it here before the
# first run if you like; after the first run, re-seeding is a no-op.
DEMO_PASSWORD=TuTakDemo-2026!

# Where the browser reaches the API. Change the host if you want to open
# the dashboards from another device on your network — see docs/TESTING_RU.md.
PUBLIC_API_BASE_URL=http://localhost:4000/v1
CORS_ORIGINS=http://localhost:3000,http://localhost:3001
EOF
  green "  ✓ .env created"
else
  info ".env already exists — keeping your secrets"
fi

# shellcheck disable=SC1091
set -a; source .env; set +a
DEMO_PASSWORD="${DEMO_PASSWORD:-TuTakDemo-2026!}"

# ── 2. Build and start ──────────────────────────────────────────────────
info "Building images (first run takes a few minutes; later runs are cached)"
docker compose build

info "Starting postgres, redis, api, admin, partner"
docker compose up -d

info "Waiting for the API to report healthy"
for i in $(seq 1 90); do
  status="$(docker compose ps --format '{{.Health}}' api 2>/dev/null | head -1)"
  [[ "$status" == "healthy" ]] && break
  if [[ $i -eq 90 ]]; then
    docker compose logs --tail 60 api
    die "The API did not become healthy. Its last 60 log lines are above."
  fi
  sleep 2
done
green "  ✓ API healthy"

# ── 3. Data ─────────────────────────────────────────────────────────────
# Migrations already ran in the API's entrypoint. These two seeds are both
# idempotent, so re-running this script never duplicates anything.
info "Seeding roles, permissions and the super admin"
docker compose exec -T \
  -e SEED_ADMIN_PASSWORD="$DEMO_PASSWORD" \
  api node dist/scripts/seed-baseline.js

info "Seeding demo partners, customers, EV stations and a full money flow"
docker compose exec -T \
  -e TUTAK_DEMO=1 \
  -e DEMO_PASSWORD="$DEMO_PASSWORD" \
  api node dist/scripts/seed-demo.js

# ── 4. Where to go ──────────────────────────────────────────────────────
cat <<EOF

────────────────────────────────────────────────────────────────────────
$(bold ' TuTak is running.')

 Admin panel        http://localhost:3000
 Partner dashboard  http://localhost:3001
 API                http://localhost:4000/v1
 API docs (Swagger) http://localhost:4000/docs

 $(bold 'Logins')  — password for all of them: $DEMO_PASSWORD

   Super admin        +37400000000
   Partner owner      +37477200001   (Cafe Yerevan — has all the money data)
   Partner owner      +37477200003   (TuTak Market — payouts blocked by drift)
   Partner staff      +37477200002   (Cafe Yerevan — can issue QR codes)
   Customer           +37477100001   (has bonus points and history)
   Customer           +37477100002 / +37477100003 / +37477100004

 Mobile app (Expo Go on your phone — needs Node + pnpm installed):
   API_BASE_URL=http://<your-LAN-ip>:4000/v1 pnpm --filter @tutak/mobile start

 Stop it all:   ./scripts/demo-down.sh
 Follow logs:   docker compose logs -f api

 What to click through: docs/TESTING_RU.md
────────────────────────────────────────────────────────────────────────
EOF
