/**
 * The one decision that lets this app answer itself instead of a server.
 *
 * It is isolated into its own file, with its own tests, because of what it
 * would cost to get wrong. The mock transport accepts **any** credentials —
 * that is deliberate and correct for a preview with nothing to authenticate
 * against, and it is a complete authentication bypass if it ever ran in a
 * build somebody installed as TuTak.
 *
 * ## Two independent keys, both required
 *
 * `useMocks` alone is one boolean between a demonstration and a bypass, and
 * one boolean is not enough distance. So the build must *also* declare itself
 * a demonstration by name.
 *
 *  - `extra.useMocks === true` — set only by `demo/app.json`, which is
 *    generated by `scripts/build-demo-app.sh` and exists nowhere else.
 *  - `extra.appEnv === 'demo'` — the production config (`app.config.js`)
 *    derives `appEnv` from `APP_ENV`, and refuses outright to build when that
 *    is `demo`. There is no EAS profile that can produce this value.
 *
 * A build that sets one and not the other talks to the real API. That is the
 * safe direction: a misconfigured demo fails to load data, which is visible
 * immediately, while a misconfigured production build would silently let
 * anybody in.
 *
 * ## Why not `__DEV__`
 *
 * Because a development build pointed at a real API must reach that API. The
 * question is not "is this a debug build", it is "is this the demonstration",
 * and only configuration can answer it.
 */
export interface MockGateConfig {
  useMocks?: unknown;
  appEnv?: unknown;
}

/** The value `appEnv` must hold. Deliberately not exported to the config. */
export const DEMO_APP_ENV = 'demo';

export function shouldUseMocks(extra: MockGateConfig | null | undefined): boolean {
  if (!extra) return false;
  return extra.useMocks === true && extra.appEnv === DEMO_APP_ENV;
}
